<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Utiliser des polices personnalisées Qt en C++</div></a></div></div><div class="Body2 Orange">Le but de ce tutoriel est de vous apprendre à utiliser des polices personnalisées <b>Qt </b>en <b>C++</b>.<br>Version Pro &amp; Industrielle. Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><b>Qt </b>est une API orientée objet et développée en C++. Qt offre des composants d'interface graphique (widgets), d'accès aux données, de connexions réseaux, de gestion des fils d'exécution, d'analyse XML. Elle utilse le mécanisme des signaux et slots.Qt prend en charge le système graphique X Window System et intègre des bindings avec plusieurs langages.<br><br><div class="Img3 GImage"><img src="/Tutoriels/Cpp/img/b_qt_font.png" alt="/Tutoriels/Cpp/img/b_qt_font.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Utiliser des polices personnalisées Qt en C++"><a class="Link3" href="#">Utiliser des polices personnalisées Qt en C++</a></h1><div class="Body3"><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1599250744051"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1599250744051");</script></div><br><h2 class="Title7 GTitle2" id="Utiliser des polices personnalisées Qt en C++-Introduction"><a class="Link9" href="#Utiliser des polices personnalisées Qt en C++">Introduction</a></h2><br>Dans l'exemple qui suit, nous essayons d'utiliser des polices personnalisées (Google Fonts).<br><br><h2 class="Title7 GTitle2" id="Utiliser des polices personnalisées Qt en C++-Programme principal"><a class="Link9" href="#Utiliser des polices personnalisées Qt en C++">Programme principal</a></h2><br><h3 class="Title8 GTitle3">main.cpp</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">GManager::Instance()-&gt;fontLoad();</xmp></pre></div><br><h3 class="Title8 GTitle3">GManager.cpp</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">m_mgr-&gt;qt-&gt;font_list = "Lobster;Akronim;Allan;Aclonica";</xmp></pre></div><br><h3 class="Title8 GTitle3">resources.qrc</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="xml">&lt;!DOCTYPE RCC&gt;
&lt;RCC version="1.0"&gt;
    &lt;qresource prefix="/font"&gt;
        &lt;file alias="Lobster.ttf"&gt;data/font/Lobster-Regular.ttf&lt;/file&gt;
        &lt;file alias="Akronim.ttf"&gt;data/font/Akronim-Regular.ttf&lt;/file&gt;
        &lt;file alias="Allan.ttf"&gt;data/font/Allan-Regular.ttf&lt;/file&gt;
        &lt;file alias="Aclonica.ttf"&gt;data/font/Aclonica-Regular.ttf&lt;/file&gt;
    &lt;/qresource&gt;
&lt;/RCC&gt;</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Utiliser des polices personnalisées Qt en C++-Chargement des polices"><a class="Link9" href="#Utiliser des polices personnalisées Qt en C++">Chargement des polices</a></h2><br><h3 class="Title8 GTitle3">GManager.cpp</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">//===============================================
void GManager::fontLoad() {
    QStringList lFontMap = m_mgr-&gt;qt-&gt;font_list.split(";");
    for(int i = 0; i &lt; lFontMap.count(); i++) {
        QString lFontName = lFontMap.at(i);
        QString lFont = ":/font/" + lFontName + ".ttf";
        QFontDatabase::addApplicationFont(lFont);
    }
}
//===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Utiliser des polices personnalisées Qt en C++-Utilisation des polices"><a class="Link9" href="#Utiliser des polices personnalisées Qt en C++">Utilisation des polices</a></h2><br><h3 class="Title8 GTitle3">styles.qss</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="css">font-family: "Lobster";
font-family: "Akronim";
font-family: "Allan";
font-family: "Aclonica";</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Utiliser des polices personnalisées Qt en C++-Résultat"><a class="Link9" href="#Utiliser des polices personnalisées Qt en C++">Résultat</a></h2><br><div class="Img3 GImage"><img src="/Tutoriels/Cpp/img/i_qt_font.png" alt="/Tutoriels/Cpp/img/i_qt_font.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Voir Aussi"><a class="Link3" href="#">Voir Aussi</a></h1><div class="Body3">Dans cette même catégorie, vous pouvez consulter aussi :<br><br><span class="GColor1" style="color:lime;">Interface Homme-Machine Qt</span><br><br><div class="Content0 GList1"><div class="Body0" id="Loader_1601149057068"><div class="Row26">List 1 &gt; Cpp &gt; qt</div></div><script>loadList1("Loader_1601149057068","Cpp","qt");</script></div><br></div></div></div></div><br>