<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Créer un manager de données en C++</div></a></div></div><div class="Body2 Orange">Le but de ce tutoriel est de vous apprendre à créer un manager de données en <b>C++</b>.<br>Version Pro &amp; Industrielle. Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><b>C++</b> est un langage de programmation compilé permettant la programmation sous de multiples paradigmes (comme la programmation procédurale, orientée objet ou générique). Ses bonnes performances, et sa compatibilité avec le C en font un des langages de programmation les plus utilisés dans les applications où la performance est critique.<br><br><div class="Img3 GImage"><img src="/Tutoriels/Cpp/img/b_cours_manager.png" alt="/Tutoriels/Cpp/img/b_cours_manager.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Créer un manager de données C++"><a class="Link3" href="#">Créer un manager de données C++</a></h1><div class="Body3"><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1599250744051"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1599250744051");</script></div><br><h2 class="Title7 GTitle2" id="Créer un manager de données C++-Introduction"><a class="Link9" href="#Créer un manager de données C++">Introduction</a></h2><br>Dans l'exemple qui suit, nous essayons de créer un manager de données (GManager).<br><br><h2 class="Title7 GTitle2" id="Créer un manager de données C++-Programme principal"><a class="Link9" href="#Créer un manager de données C++">Programme principal</a></h2><br><h3 class="Title8 GTitle3">main.cpp</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">sGQt* lQt = GManager::Instance()-&gt;dataGet()-&gt;qt;
setWindowTitle(lQt-&gt;title);
resize(lQt-&gt;width, lQt-&gt;height);</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un manager de données C++-Déclaration du manager de données"><a class="Link9" href="#Créer un manager de données C++">Déclaration du manager de données</a></h2><br><h3 class="Title8 GTitle3">GManager.h</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">sGManager* m_mgr;</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un manager de données C++-Structure du manager de données"><a class="Link9" href="#Créer un manager de données C++">Structure du manager de données</a></h2><br><h3 class="Title8 GTitle3">GManager.h</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">//===============================================
struct _sGManager {
    sGQt* qt;
};
//===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un manager de données C++-Structure du manager de données Qt"><a class="Link9" href="#Créer un manager de données C++">Structure du manager de données Qt</a></h2><br><h3 class="Title8 GTitle3">GManager.h</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">//===============================================
struct _sGQt {
    QString title;
    int width;
    int height;
};
//===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un manager de données C++-Création du manager de données"><a class="Link9" href="#Créer un manager de données C++">Création du manager de données</a></h2><br><h3 class="Title8 GTitle3">GManager.cpp</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">// manager
m_mgr = new sGManager;</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un manager de données C++-Création du manager de données Qt"><a class="Link9" href="#Créer un manager de données C++">Création du manager de données Qt</a></h2><br><h3 class="Title8 GTitle3">GManager.cpp</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">// qt
m_mgr-&gt;qt = new sGQt;
m_mgr-&gt;qt-&gt;title = "ReadyApp";
m_mgr-&gt;qt-&gt;width = 640;
m_mgr-&gt;qt-&gt;height = 480;</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un manager de données C++-Lecture du manager de données"><a class="Link9" href="#Créer un manager de données C++">Lecture du manager de données</a></h2><br><h3 class="Title8 GTitle3">GManager.cpp</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">//===============================================
sGManager* GManager::dataGet() {
    return m_mgr;
}
//===============================================</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Voir Aussi"><a class="Link3" href="#">Voir Aussi</a></h1><div class="Body3">Dans cette même catégorie, vous pouvez consulter aussi :<br><br><span class="GColor1" style="color:lime;">Programmation de base</span><br><br><div class="Content0 GList1"><div class="Body0" id="Loader_1600474250946"><div class="Row26">List 1 &gt; Cpp &gt; basics</div></div><script>loadList1("Loader_1600474250946","Cpp","basics");</script></div><br></div></div></div></div><br>