<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Modélisation 3D avec Blender<br></div></a></div></div><div class="Body2 Orange">Le but de ce tutoriel est de vous apprendre la modélisation 3D avec <b>Blender</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div><br></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><br><b>Blender </b>est un outil de modélisation 3D.<br><br><div class="Img3 GImage"><img src="/Tutoriels/3D_Modeling/Blender/img/b_blender.png" alt="/Tutoriels/3D_Modeling/Blender/img/b_blender.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Installation"><a class="Link3" href="#">Installation</a></h1><div class="Body3"><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1616453772347"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1616453772347");</script></div><br><h2 class="Title7 GTitle2" id="Installation-1 - Installation sous Windows"><a class="Link9" href="#Installation">1 - Installation sous Windows</a></h2><br><h2 class="Title7 GTitle2" id="Installation-1.1 - Télécharger Blender"><a class="Link9" href="#Installation">1.1 - Télécharger Blender</a></h2><br><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://ftp.nluug.nl/pub/graphics/blender/release/Blender2.92/blender-2.92.0-windows64.msi">https://ftp.nluug.nl/pub/graphics/blender/release/Blender2.92/blender-2.92.0-windows64.msi</a><br><br><h2 class="Title7 GTitle2" id="Installation-1.2 - Installer Blender"><a class="Link9" href="#Installation">1.2 - Installer Blender</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">blender-2.92.0-windows64.msi
Next
Check -&gt; I accept the terms in the License Agreement
Next
Location -&gt; C:\Program Files\Blender Foundation\Blender 2.92\
Next
Install
Finish</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Installation-1.3 - Démarrer Blender"><a class="Link9" href="#Installation">1.3 - Démarrer Blender</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Windows
Blender</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Installation-1.4 - Problèmes de démarrage"><a class="Link9" href="#Installation">1.4 - Problèmes de démarrage</a></h2><br><h2 class="Title7 GTitle2" id="Installation-1.4.1 - Résoudre le problème lié au driver OpenGL 3.3"><a class="Link9" href="#Installation">1.4.1 - Résoudre le problème lié au driver OpenGL 3.3</a></h2><br><h2 class="Title7 GTitle2" id="Installation-1.4.1.1 - Déterminer le type de la carte graphique"><a class="Link9" href="#Installation">1.4.1.1 - Déterminer le type de la carte graphique</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Windows
Right click -&gt; Paramètres d'affichage
Affichage
Plusieurs affichages
Paramètres d'affichage avancés
Afficher les informations
Propriétés de la carte vidéo pour l'affichage 1
Carte
Type de carte
Intel(R) HD Graphics 3000</xmp></pre></div><br>La carte graphique <span class="GColor1" style="color:lime;">Intel(R) HD Graphics 3000</span> supporte <span class="GColor1" style="color:lime;">OpenGL 3.1</span>.<br><br>Il nous faut au minimum <span class="GColor1" style="color:cyan;">OpenGL 3.3</span> pour démarrer<span class="GColor1" style="color:cyan;"> Blender 2.92</span>.<br><br><h2 class="Title7 GTitle2" id="Installation-1.4.1.2 - Télécharger la DLL OpenGL 3.3"><a class="Link9" href="#Installation">1.4.1.2 - Télécharger la DLL OpenGL 3.3</a></h2><br><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://drive.google.com/file/d/19teTBNis9jRk99gEt991-SyTVxSaiDwv/view">https://drive.google.com/file/d/19teTBNis9jRk99gEt991-SyTVxSaiDwv/view</a><br><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Opengl By Rexo Web.zip</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Installation-1.4.1.3 - Installer la DLL OpenGL"><a class="Link9" href="#Installation">1.4.1.3 - Installer la DLL OpenGL</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Windows
Extract -&gt; Opengl By Rexo Web.zip -&gt; opengl32.dll
Copy -&gt; opengl32.dll
Paste -&gt; C:\Program Files\Blender Foundation\Blender 2.92 -&gt; opengl32.dll</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Installation-1.4.1.4 - Démarrer Blender"><a class="Link9" href="#Installation">1.4.1.4 - Démarrer Blender</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Windows
Blender</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Panneaux"><a class="Link3" href="#">Panneaux</a></h1><div class="Body3"><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1616459631275"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1616459631275");</script></div><br><h2 class="Title7 GTitle2" id="Panneaux-1 - Panneau"><a class="Link9" href="#Panneaux">1 - Panneau</a></h2><br>Blender est constitué de :<br><br>$\checkmark$ Plusieurs panneaux.<br><br>Un panneau est constitué de :<br><br>$\checkmark$ Une entête<br>$\checkmark$ Un contenu<br><br><h2 class="Title7 GTitle2" id="Panneaux-1.1 - Entête"><a class="Link9" href="#Panneaux">1.1 - Entête</a></h2><br>Une entête est constituée de :<br><br>$\checkmark$ Une liste déroulante<br>$\checkmark$ Une barre d'outils<br><br><h2 class="Title7 GTitle2" id="Panneaux-1.1.1 - Liste déroulante"><a class="Link9" href="#Panneaux">1.1.1 - Liste déroulante</a></h2><br>Une liste déroulante est constitué de :<br><br>$\checkmark$ Plusieurs éléments de menu<br><br><h2 class="Title7 GTitle2" id="Panneaux-1.1.2 - Barre d'outils"><a class="Link9" href="#Panneaux">1.1.2 - Barre d'outils</a></h2><br>Une barre d'outils est constitué de :<br><br>$\checkmark$ Plusieurs outils<br><br>L'apparence d'une barre d'outils change en fonction du choix de l'élément de menu.<br><br><h2 class="Title7 GTitle2" id="Panneaux-1.2 - Contenu"><a class="Link9" href="#Panneaux">1.2 - Contenu</a></h2><br>L'apparence d'un contenu change en fonction du choix de l'élément de menu.<br><br><h2 class="Title7 GTitle2" id="Panneaux-2 - Opérations"><a class="Link9" href="#Panneaux">2 - Opérations</a></h2><br><h2 class="Title7 GTitle2" id="Panneaux-2.1 - Diviser un panneau"><a class="Link9" href="#Panneaux">2.1 - Diviser un panneau</a></h2><br><h2 class="Title7 GTitle2" id="Panneaux-2.1.1 - Diviser un panneau verticalement"><a class="Link9" href="#Panneaux">2.1.1 - Diviser un panneau verticalement</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Positionner -&gt; Souris -&gt; Intersection panneaux
Clic droit -&gt; Split Vertical
Clic gauche</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Panneaux-2.1.2 - Diviser un panneau horizontalement"><a class="Link9" href="#Panneaux">2.1.2 - Diviser un panneau horizontalement</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Positionner -&gt; Souris -&gt; Intersection panneaux
Clic droit -&gt; Split Horizontal
Clic gauche</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Panneaux-2.2 - Supprimer un panneau"><a class="Link9" href="#Panneaux">2.2 - Supprimer un panneau</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Positionner -&gt; Souris -&gt; Intersection panneaux
Clic droit -&gt; Join Areas
Clic gauche</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Panneaux-2.3 - Extraire un panneau"><a class="Link9" href="#Panneaux">2.3 - Extraire un panneau</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Positionner -&gt; Souris -&gt; Coin droit panneau
Extraire -&gt; Panneau -&gt; Shift + Clic gauche + Glisser</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Panneaux-2.4 - Fermer un panneau extrait"><a class="Link9" href="#Panneaux">2.4 - Fermer un panneau extrait</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Clic gauche -&gt; Fermer</xmp></pre></div><br>Cette action n'a aucune influence sur la fenêtre principale.<br><br><br></div></div></div></div><br>