<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Créer un projet en PHP</div></a></div></div><div class="Body2 Orange">Le but de ce tutoriel est de vous apprendre à créer un projet en <b>PHP</b>.<br>Version Pro &amp; Industrielle. Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><b>PHP </b>est un langage de programmation orientée objet utilisé pour produire des pages Web dynamiques via un serveur HTTP. Il peut être aussi utilisé comme n'importe quel langage interprété de façon locale. Il a permis de créer un grand nombre de sites web célèbres, comme Facebook et Wikipédia. Il est considéré comme une des bases de la création de sites web dits dynamiques mais également des applications web.<br><br><div class="Img3 GImage"><img src="/Tutoriels/PHP/img/b_cours_project.png" alt="/Tutoriels/PHP/img/b_cours_project.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Créer un projet en PHP"><a class="Link3" href="#">Créer un projet en PHP</a></h1><div class="Body3"><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1599250744051"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1599250744051");</script></div><br><h2 class="Title7 GTitle2" id="Créer un projet en PHP-Introduction"><a class="Link9" href="#Créer un projet en PHP">Introduction</a></h2><br>Dans l'exemple qui suit, nous essayons de créer un projet en PHP qui affiche un message à l'écran (Bonjour tout le monde).<br><br><h2 class="Title7 GTitle2" id="Créer un projet en PHP-Programme principal"><a class="Link9" href="#Créer un projet en PHP">Programme principal</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="php">&lt;?php
//=================================================
echo "<h1>Bonjour tout le monde</h1>";
//=================================================
?&gt;</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un projet en PHP-Autoriser le module CGI"><a class="Link9" href="#Créer un projet en PHP">Autoriser le module CGI</a></h2><br><h3 class="Title8 GTitle3">httpd.conf</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">LoadModule cgi_module modules/mod_cgi.so</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un projet en PHP-Autoriser le module rewrite"><a class="Link9" href="#Créer un projet en PHP">Autoriser le module rewrite</a></h2><br><h3 class="Title8 GTitle3">httpd.conf</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">LoadModule rewrite_module modules/mod_rewrite.so</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un projet en PHP-Autoriser les machines virtuelles"><a class="Link9" href="#Créer un projet en PHP">Autoriser les machines virtuelles</a></h2><br><h3 class="Title8 GTitle3">httpd.conf</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">LoadModule vhost_alias_module modules/mod_vhost_alias.so</xmp></pre></div><br><h3 class="Title8 GTitle3">httpd.conf</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">Include conf/extra/httpd-vhosts.conf</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un projet en PHP-Configurer le port du serveur"><a class="Link9" href="#Créer un projet en PHP">Configurer le port du serveur</a></h2><br><h3 class="Title8 GTitle3">httpd.conf</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">Listen 0.0.0.0:8800
Listen [::0]:8800</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un projet en PHP-Configurer la racine du serveur"><a class="Link9" href="#Créer un projet en PHP">Configurer la racine du serveur</a></h2><br><h3 class="Title8 GTitle3">httpd-vhosts.conf</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">#================================================
&lt;VirtualHost *:8800&gt;
    ServerName www.readydev.com
    ServerAdmin gerard.kesse@outlook.fr
    DocumentRoot "C:/Users/Admin/Downloads/Programs/ReadyDev"
    &lt;Directory "C:/Users/Admin/Downloads/Programs/ReadyDev"&gt;
        Options All
        AllowOverride All
        Order allow,deny
        allow from all
        Require all granted
    &lt;/Directory&gt;
&lt;/VirtualHost&gt;
#================================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un projet en PHP-Redémarrer le serveur"><a class="Link9" href="#Créer un projet en PHP">Redémarrer le serveur</a></h2><br><h3 class="Title8 GTitle3">Windows</h3><br>WampServer → Redémarrer les services<br><br><h2 class="Title7 GTitle2" id="Créer un projet en PHP-Accéder à la page web"><a class="Link9" href="#Créer un projet en PHP">Accéder à la page web</a></h2><br><h3 class="Title8 GTitle3">Navigateur</h3><br><a class="Link7 GLink1" style="color:lime;" target="_blank" href="http://localhost:8800/">http://localhost:8800/</a><br><br><h2 class="Title7 GTitle2" id="Créer un projet en PHP-Résultat"><a class="Link9" href="#Créer un projet en PHP">Résultat</a></h2><br><div class="Img3 GImage"><img src="/Tutoriels/PHP/img/i_cours_project.png" alt="/Tutoriels/PHP/img/i_cours_project.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Voir Aussi"><a class="Link3" href="#">Voir Aussi</a></h1><div class="Body3">Dans cette même catégorie, vous pouvez consulter aussi :<br><br><span class="GColor1" style="color:lime;">Programmation de base</span><br><br><div class="Content0 GList1"><div class="Body0" id="Loader_1600429735365"><div class="Row26">List 1 &gt; PHP &gt; basics</div></div><script>loadList1("Loader_1600429735365","PHP","basics");</script></div><br></div></div></div></div><br>