<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Ingénieur Développeur Logiciel C/C++/Qt</div></a></div></div><div class="Body2 Orange">Je suis <b>Gérard KESSE</b>,<br>Ingénieur en Développement Informatique C/C++/Qt,<br>Avec à la fois des compétences en <b>Système Embarqué</b> et en <b>Robotique</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1569674769632"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1569674769632");</script></div><br><div class="Content0 GHtml1"><div class="Center">
    <a class="Link5" href="/CV/Simplifie/">
        <div class="Text2">CV<br>Simplifié</div>
        <i class="Icon3 fa fa-file-pdf-o"></i>
    </a> 
    &nbsp;
    <a class="Link5" href="/CV/Detaille/">
        <div class="Text2">CV<br>Détaillé</div>
        <i class="Icon3 fa fa-file-pdf-o"></i>
    </a>                        
</div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Diplomes"><a class="Link3" href="#">Diplômes</a></h1><div class="Body3"><div class="Content0 GList3"><div class="Body0" id="Loader_1569700628842"><div class="Row26">List 3 &gt; CV &gt; graduation</div></div><script>loadList3("Loader_1569700628842","CV","graduation");</script></div></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Certificats"><a class="Link3" href="#">Certificats</a></h1><div class="Body3"><div class="Content0 GList3"><div class="Body0" id="Loader_1569700750580"><div class="Row26">List 3 &gt; CV &gt; certificate</div></div><script>loadList3("Loader_1569700750580","CV","certificate");</script></div></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Parcours-professionnels"><a class="Link3" href="#">Parcours professionnels</a></h1><div class="Body3"><div class="Content0 GList3"><div class="Body0" id="Loader_1569700838999"><div class="Row26">List 3 &gt; CV &gt; career</div></div><script>loadList3("Loader_1569700838999","CV","career");</script></div></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Competences-Informatiques"><a class="Link3" href="#">Compétences Informatiques</a></h1><div class="Body3"><div class="Content0 GList3"><div class="Body0" id="Loader_1569700992638"><div class="Row26">List 3 &gt; CV &gt; skill</div></div><script>loadList3("Loader_1569700992638","CV","skill");</script></div></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Langues"><a class="Link3" href="#">Langues</a></h1><div class="Body3"><div class="Content0 GList3"><div class="Body0" id="Loader_1569701164258"><div class="Row26">List 3 &gt; CV &gt; language</div></div><script>loadList3("Loader_1569701164258","CV","language");</script></div></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Experiences-Professionnelles"><a class="Link3" href="#">Expériences Professionnelles</a></h1><div class="Body3"><div class="Content0 GList4"><div class="Body0" id="Loader_1569702858138"><div class="Row26">List 4 &gt; CV &gt; experience</div></div><script>loadList4("Loader_1569702858138","CV","experience");</script></div></div></div></div></div><br>