<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Apprendre la gestion de données Git avec GitHub</div></a></div></div><div class="Body2 Orange"><b>Git</b> est un système de gestion de versions.<br><b>GitHub </b>est un hébergeur web de données <b>Git</b>.<br>Le but de ce tutoriel est de vous apprendre la gestion de données <b>Git </b>avec <b>GitHub</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Installation sous Windows"><a class="Link3" href="#">Installation sous Windows</a></h1><div class="Body3">Le but de cette section est de vous présenter les différents outils nécessaires pour apprendre la gestion de données <span class="GColor1" style="color:lime;">Git </span>avec <span class="GColor1" style="color:lime;">GitHub</span><span class="GColor1" style="color:lime;"></span>, sous Windows.<br>Produit par <b>Gérard KESSE</b>.<br><br>Dans ce tutoriel, nous utiliserons, sous Windows:<br>- Git, comme système de gestion de versions.<br>- GitHub, comme serveur de données Git.<br>- Outlook, comme serveur de méssagerie web.<br>- Notepad++, comme éditeur de texte.<br><br><h3 class="Title8 GTitle3">Télécharger Git</h3><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://git-scm.com/downloads">https://git-scm.com/downloads</a><br><br><h3 class="Title8 GTitle3">Accéder à GitHub</h3><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://github.com/">https://github.com/</a><br><br><h3 class="Title8 GTitle3">Accéder à Outlook</h3><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://outlook.com/">https://outlook.com/</a><br><br><h3 class="Title8 GTitle3">Télécharger Notepad++</h3><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://notepad-plus-plus.org/">https://notepad-plus-plus.org/</a><br></div></div></div></div>
<br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Créer un compte e-mail avec Outlook"><a class="Link3" href="#">Créer un compte e-mail avec Outlook</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Créer un compte e-mail </span>avec Outlook.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576922312395"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576922312395");</script></div><br><h2 class="Title7 GTitle2" id="Créer un compte e-mail avec Outlook-Créer le compte e-mail"><a class="Link9" href="#Créer un compte e-mail avec Outlook">Créer le compte e-mail</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">outlook
creer gratuitement un compte
email
mot de passe
prenom
nom
pays
date de naissance</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Créer un compte avec GitHub"><a class="Link3" href="#">Créer un compte avec GitHub</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Créer un compte </span>avec GitHub.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576923744585"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576923744585");</script></div><br><h2 class="Title7 GTitle2" id="Créer un compte avec GitHub-Créer le compte GitHub"><a class="Link9" href="#Créer un compte avec GitHub">Créer le compte GitHub</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">github
sign up
username
email
password
plan: free
programming experience: new to programming
plan: use github api
interested
verify email address</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Se connecter à un compte avec GitHub"><a class="Link3" href="#">Se connecter à un compte avec GitHub</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Se connecter à un compte</span> avec GitHub.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1577015795522"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1577015795522");</script></div><br><h2 class="Title7 GTitle2" id="Se connecter à un compte avec GitHub-Se connecter au compte"><a class="Link9" href="#Se connecter à un compte avec GitHub">Se connecter au compte</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">github
sign in
username or email
password
</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Se déconnecter à un compte avec GitHub"><a class="Link3" href="#">Se déconnecter à un compte avec GitHub</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Se déconnecter à un compte </span>avec GitHub.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1577015937984"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1577015937984");</script></div><br><h2 class="Title7 GTitle2" id="Se déconnecter à un compte avec GitHub-Se déconnecter au compte"><a class="Link9" href="#Se déconnecter à un compte avec GitHub">Se déconnecter au compte</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">github
profile menu
sign out</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Éditer un profil avec GitHub"><a class="Link3" href="#">Éditer un profil avec GitHub</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Éditer un profil </span>avec GitHub.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576946222533"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576946222533");</script></div><br><h2 class="Title7 GTitle2" id="Éditer un profil avec GitHub-Éditer le profil"><a class="Link9" href="#Éditer un profil avec GitHub">Éditer le profil</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">github
profil menu
your profil
edit profil
biography
company
location
website</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Changer la photo d'un profil avec GitHub"><a class="Link3" href="#">Changer la photo d'un profil avec GitHub</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Changer la photo d'un profil </span>avec GitHub.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576947103045"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576947103045");</script></div><br><h2 class="Title7 GTitle2" id="Changer la photo d'un profil avec GitHub-Changer la photo du profil"><a class="Link9" href="#Changer la photo d'un profil avec GitHub">Changer la photo du profil</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">github
profile menu
your profile
settings
profile picture</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Créer un dépôt avec GitHub"><a class="Link3" href="#">Créer un dépôt avec GitHub</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Créer un dépôt </span>avec GitHub.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576947613856"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576947613856");</script></div><br><h2 class="Title7 GTitle2" id="Créer un dépôt avec GitHub-Créer le dépôt"><a class="Link9" href="#Créer un dépôt avec GitHub">Créer le dépôt</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">github
add menu
new repository
owner
repository name
description
public
readme
.gitignore : c
license : gnu general public license</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Cloner un dépôt avec Git"><a class="Link3" href="#">Cloner un dépôt avec Git</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Cloner un dépôt </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1577011670336"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1577011670336");</script></div><br><h2 class="Title7 GTitle2" id="Cloner un dépôt avec Git-Cloner le dépôt"><a class="Link9" href="#Cloner un dépôt avec Git">Cloner le dépôt</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">set GPROJECT=C:\Users\Admin\Downloads\Programs\ReadyGithub\pierre
cd %GPROJECT%
git clone https://github.com/pierreyuri/ReadyGithub.git projet</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Afficher toutes les branches avec Git"><a class="Link3" href="#">Afficher toutes les branches avec Git</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Afficher toutes les branches </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1577012314943"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1577012314943");</script></div><br><h2 class="Title7 GTitle2" id="Afficher toutes les branches avec Git-Afficher toutes les branches avec Git"><a class="Link9" href="#Afficher toutes les branches avec Git">Afficher toutes les branches avec Git</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">set GPROJECT=C:\Users\Admin\Downloads\Programs\ReadyGithub\pierre\projet
cd %GPROJECT%
git branch --all</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Afficher tous les dépôts distants avec Git"><a class="Link3" href="#">Afficher tous les dépôts distants avec Git</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Afficher tous les dépôts distants </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1577012893968"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1577012893968");</script></div><br><h2 class="Title7 GTitle2" id="Afficher tous les dépôts distants avec Git-Afficher tous les dépôts distants avec Git"><a class="Link9" href="#Afficher tous les dépôts distants avec Git">Afficher tous les dépôts distants avec Git</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">set GPROJECT=C:\Users\Admin\Downloads\Programs\ReadyGithub\pierre\projet
cd %GPROJECT%
git remote -v</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Afficher le status d'un dépôt avec Git"><a class="Link3" href="#">Afficher le status d'un dépôt avec Git</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Afficher le status d'un dépôt </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1577013131871"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1577013131871");</script></div><br><h2 class="Title7 GTitle2" id="Afficher le status d'un dépôt avec Git-Afficher le status du dépôt"><a class="Link9" href="#Afficher le status d'un dépôt avec Git">Afficher le status du dépôt</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">set GPROJECT=C:\Users\Admin\Downloads\Programs\ReadyGithub\pierre\projet
cd %GPROJECT%
git status</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Créer une branche avec Git"><a class="Link3" href="#">Créer une branche avec Git</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Créer une branche </span>avec GitHub.<br><br>On décide de créer un programme en C, avec MinGW, sous Eclipse permettant d'afficher un message à l'écran (<b>Bonjour tout le monde</b>).<br>On décide de développer le projet avec une architecture simple (<b>main.c</b>).<br>On décide de Créer une branche avec Git (<b>simple</b>) pour gérer le développement.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576951658410"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576951658410");</script></div><br><h2 class="Title7 GTitle2" id="Créer une branche avec Git-Créer la branche"><a class="Link9" href="#Créer une branche avec Git">Créer la branche</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">set GPROJECT=C:\Users\Admin\Downloads\Programs\ReadyGithub\pierre\projet
cd %GPROJECT%
git checkout -b simple master</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer une branche avec Git-Indexer tous les fichiers"><a class="Link9" href="#Créer une branche avec Git">Indexer tous les fichiers</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">set GPROJECT=C:\Users\Admin\Downloads\Programs\ReadyGithub\pierre\projet
cd %GPROJECT%
git add --all</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer une branche avec Git-Valider les modifications"><a class="Link9" href="#Créer une branche avec Git">Valider les modifications</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">set GPROJECT=C:\Users\Admin\Downloads\Programs\ReadyGithub\pierre\projet
cd %GPROJECT%
git commit -m "developpement du systeme simple"</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer une branche avec Git-Pousser les modifications"><a class="Link9" href="#Créer une branche avec Git">Pousser les modifications</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">set GPROJECT=C:\Users\Admin\Downloads\Programs\ReadyGithub\pierre\projet
cd %GPROJECT%
git push -u origin simple</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Afficher les branches avec GitHub"><a class="Link3" href="#">Afficher les branches avec GitHub</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Afficher les branches </span>avec GitHub.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1577022681561"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1577022681561");</script></div><br><h2 class="Title7 GTitle2" id="Afficher les branches avec GitHub-Afficher les branches"><a class="Link9" href="#Afficher les branches avec GitHub">Afficher les branches</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">github
profile menu
your profile
repositories
repository
code
branches
branch</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Afficher les commits avec GitHub"><a class="Link3" href="#">Afficher les commits avec GitHub</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Afficher les commits </span>avec GitHub.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1577022741719"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1577022741719");</script></div><br><h2 class="Title7 GTitle2" id="Afficher les commits avec GitHub-Afficher les commits"><a class="Link9" href="#Afficher les commits avec GitHub">Afficher les commits</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">github
profile menu
your profile
repositories
repository
code
branch
commits</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Changer les identifiants git sous Windows"><a class="Link3" href="#">Changer les identifiants git sous Windows</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Changer les identifiants git </span>sous Windows.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1577002484344"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1577002484344");</script></div><br><h2 class="Title7 GTitle2" id="Changer les identifiants git sous Windows-Changer les identifiants git"><a class="Link9" href="#Changer les identifiants git sous Windows">Changer les identifiants git</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">windows
panneau de configuration
tous les Panneaux de configuration
gestionnaire d'identification
informations d'identification windows
informations d'identification generiques
git:https://github.com
modifier
nom d'utilisateur
mot de passe</xmp></pre></div><br></div></div></div></div><br>