<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Chute libre<br></div></a></div></div><div class="Body2 Orange">Le but de ce tutoriel est de vous apprendre la chute libre en <b>Physique</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3">La <b>Physique </b>est la science qui essaie de comprendre, de modéliser et d'expliquer les phénomènes naturels de l'univers. Elle correspond à l'étude du monde qui nous entoure sous toutes ses formes, des lois de sa variation et de son évolution. <br><br><div class="Img3 GImage"><img src="/data/img/defaults/banner_physics_free_fall.png" alt="/data/img/defaults/banner_physics_free_fall.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Chute libre"><a class="Link3" href="#">Chute libre</a></h1><div class="Body3"><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1598441695432"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1598441695432");</script></div><br><h2 class="Title7 GTitle2" id="Chute libre-Utilité"><a class="Link9" href="#Chute libre">Utilité</a></h2><br>$\checkmark$ Déterminer l'équation du mouvement d'un objet uniquement soumis à sa pésenteur.<br><br><h2 class="Title7 GTitle2" id="Chute libre-Schéma fonctionnel"><a class="Link9" href="#Chute libre">Schéma fonctionnel</a></h2><br><div class="Img3 GImage"><img src="/Cours/Physics/img/free_fall.png" alt="/Cours/Physics/img/free_fall.png"></div><br><h2 class="Title7 GTitle2" id="Chute libre-Équation du mouvement"><a class="Link9" href="#Chute libre">Équation du mouvement</a></h2><br>Soient $\vec{a}$, l'accélération de l'objet, $m$ sa masse et $\vec{P}$ son poids.<br><br>Loi fondamentale de la dynamique :<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\vec{P} &amp;=&amp; m\vec{a}\\
\end{eqnarray}</div></div><br>On an :<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\vec{P} &amp;=&amp; m\vec{g}\\
\end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
m\vec{g} &amp;=&amp; m\vec{a}\\
\end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\vec{a} &amp;=&amp; \vec{g}\\
\end{eqnarray}</div></div><br>Projection sur l'axe $z$ :<br><br><div class="Formula GFormula1"><div class="Formula5">\begin{eqnarray} 
a_z &amp;=&amp; -g
\end{eqnarray}</div></div><br>On a :<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
a_z &amp;=&amp; \frac{dv}{dt}
\end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} \frac{dv}{dt}
&amp;=&amp; -g \end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} dv
&amp;=&amp; -gdt \end{eqnarray}<br></div></div><div class="Content0 GHtml1"><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} \int_{v_0}^{v}dv &amp;=&amp; -g\int_{t_0}^{t}dt \end{eqnarray}</div></div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} v-v_0
&amp;=&amp; -g(t-t_0) \end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} v
&amp;=&amp; -g(t-t_0)+v_0 \end{eqnarray}</div></div><br>Posons :<br><br><div class="Formula GFormula1"><div class="Formula2">$$\left \{
\begin{array}{r c l} t_0 &amp; = &amp; 0 \\
v_0 &amp; = &amp; 0
\end{array}
\right .$$</div></div><div class="Formula GFormula1"><div class="Formula5">\begin{eqnarray} v &amp;=&amp; -gt
\end{eqnarray}</div></div><br>On a :<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
v &amp;=&amp; \frac{dz}{dt} \end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray}&nbsp; \frac{dz}{dt} &amp;=&amp; -gt
\end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} dz
&amp;=&amp; -gtdt \end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} \int_{z_0}^{z}dz &amp;=&amp; -g\int_{t_0}^{t}tdt \end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} z-z_0 &amp;=&amp; -\frac{1}{2}g\left(t^2-t_0^2\right) \end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula5">\begin{eqnarray} z
&amp;=&amp; -\frac{1}{2}gt^2+z_0 \end{eqnarray}</div></div><br><h2 class="Title7 GTitle2" id="Chute libre-Impact au sol"><a class="Link9" href="#Chute libre">Impact au sol</a></h2><br>Impact au sol :<br><br><div class="Formula GFormula1"><div class="Formula2">$$\left \{ \begin{array}{r c l} z &amp; = &amp; 0 \\ t &amp; = &amp; t_1 \\ v &amp; = &amp; v_1 \end{array} \right .$$</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 0 &amp;=&amp; -\frac{1}{2}gt_1^2+z_0 \end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} \frac{1}{2}gt_1^2 &amp;=&amp; z_0 \end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} t_1^2 &amp;=&amp; \frac{2z_0}{g} \end{eqnarray}</div></div><div class="Formula5">\begin{eqnarray} t_1 &amp;=&amp; \sqrt{\frac{2z_0}{g}} \end{eqnarray}</div><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} v_1 &amp;=&amp; -gt_1 \end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} v_1 &amp;=&amp; -g\sqrt{\frac{2z_0}{g}} \end{eqnarray}</div></div><div class="Formula GFormula1"><div class="Formula5">\begin{eqnarray} v_1 &amp;=&amp; -\sqrt{2gz_0} \end{eqnarray}</div></div><br><h2 class="Title7 GTitle2" id="Chute libre-Notes"><a class="Link9" href="#Chute libre">Notes</a></h2><br>$\checkmark$ Une variation de la position est dûe à une vitesse non nulle<br>$\checkmark$ Comme la position diminue, la vitesse algébrique est donc négative<br><br></div></div></div></div><br>