<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Charger une icône Qt en Go</div></a></div></div><div class="Body2 Orange">Le but de ce tutoriel est de vous apprendre à charger une icône Qt en <b>Go</b>.<br>Version Pro &amp; Industrielle. Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><b>Go </b>est un langage de programmation compilé et concurrent inspiré de C et Pascal. Il veut faciliter et accélérer la programmation à grande échelle en raison de sa simplicité. Il peut être utilisé aussi bien pour écrire des applications, des scripts ou de grands systèmes. Il permet d'assurer la maintenance et l'évolution des programmes sur plusieurs générations de développeurs.<br><br><div class="Img3 GImage"><img src="/Tutoriels/Go/img/b_qt_icon.png" alt="/Tutoriels/Go/img/b_qt_icon.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Charger une icône Qt en Go"><a class="Link3" href="#">Charger une icône Qt en Go</a></h1><div class="Body3"><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1599250744051"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1599250744051");</script></div><br><h2 class="Title7 GTitle2" id="Charger une icône Qt en Go-Introduction"><a class="Link9" href="#Charger une icône Qt en Go">Introduction</a></h2><br>Dans l'exemple qui suit, nous essayons de charger une icône Qt en Go.<br><br><h2 class="Title7 GTitle2" id="Charger une icône Qt en Go-Programme principal"><a class="Link9" href="#Charger une icône Qt en Go">Programme principal</a></h2><br><h3 class="Title8 GTitle3">GManager.go</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="golang">lObj.loadIconObj();</xmp></pre></div><br><h3 class="Title8 GTitle3">GManager.go</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="golang">obj.mgr.app.icon_map = make(map[string]string)</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Charger une icône Qt en Go-Chargement des icônes"><a class="Link9" href="#Charger une icône Qt en Go">Chargement des icônes</a></h2><br><h3 class="Title8 GTitle3">GManager.go</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="golang">//===============================================
func (obj *GManagerO) loadIconObj() {
    lPath := obj.mgr.app.icon_path
    lDir, _ := ioutil.ReadDir(lPath)
    for _, lFile := range lDir {
        if lFile.IsDir() == false {
            lFilename := lFile.Name()
            lFullname := lPath + "/" + lFilename
            lKey := obj.Basename(lFilename)
            obj.mgr.app.icon_map[lKey] = lFullname
        }
    }
}
//===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Charger une icône Qt en Go-Répertoire des icônes"><a class="Link9" href="#Charger une icône Qt en Go">Répertoire des icônes</a></h2><br><h3 class="Title8 GTitle3">data/img/fa/white/64</h3><br><div class="Img3 GImage"><img src="/Tutoriels/Go/img/i_qt_icon.png" alt="/Tutoriels/Go/img/i_qt_icon.png"></div><br><h2 class="Title7 GTitle2" id="Charger une icône Qt en Go-Utilisation d'une icône"><a class="Link9" href="#Charger une icône Qt en Go">Utilisation d'une icône</a></h2><br><h3 class="Title8 GTitle3">GTitleBar.go</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="golang">lApp := GManager().mgr.app
lClose := widgets.NewQPushButton(nil)
lClose.SetIcon(gui.NewQIcon5(lApp.icon_map["times"]));</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Charger une icône Qt en Go-Résultat"><a class="Link9" href="#Charger une icône Qt en Go">Résultat</a></h2><br><div class="Img3 GImage"><img src="/Tutoriels/Go/img/i_qt_icon_02.png" alt="/Tutoriels/Go/img/i_qt_icon_02.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Voir Aussi"><a class="Link3" href="#">Voir Aussi</a></h1><div class="Body3">Dans cette même catégorie, vous pouvez consulter aussi :<br><br><span class="GColor1" style="color:lime;">Interface Homme-Machine Qt</span><br><br><div class="Content0 GList1"><div class="Body0" id="Loader_1605458922954"><div class="Row26">List 1 &gt; Go &gt; qt</div></div><script>loadList1("Loader_1605458922954","Go","qt");</script></div><br></div></div></div></div><br>