<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Programmation web en HTML<br></div></a></div></div><div class="Body2 Orange"><br>Le but de ce tutoriel est de vous apprendre la programmation web en <b>HTML</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div><br></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><br>Le HyperText Markup Language, généralement abrégé <b>HTML </b>ou dans sa dernière version HTML5, est le langage de balisage conçu pour représenter les pages web. Ce langage permet : d’écrire de l’hypertexte, d’où son nom, de structurer sémantiquement la page, de mettre en forme le contenu, de créer des formulaires de saisie, d’inclure des ressources multimédias dont des images, des vidéos, et des programmes informatiques, de créer des documents interopérables avec des équipements très variés de manière conforme aux exigences de l’accessibilité du web. Il est souvent utilisé conjointement avec le langage de programmation JavaScript et des feuilles de style en cascade (CSS). HTML est inspiré du Standard Generalized Markup Language (SGML). Il s'agit d'un format ouvert.<br><br><div class="Img3 GImage"><img src="/Tutoriels/Web/HTML/img/b_html.png" alt="/Tutoriels/Web/HTML/img/b_html.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Fondamentaux"><a class="Link3" href="#">Fondamentaux</a></h1><div class="Body3"><br>Les fondamentaux de l'HTML.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1621916381426"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1621916381426");</script></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Creer-un-programme-minimal"><a class="Link9" href="#Fondamentaux">Créer un programme minimal</a></h2><br><h3 class="Title8 GTitle3">index.html</h3><br><div class="GCode1"><div class="Code2"><xmp class="AceCode" data-mode="html">&lt;!DOCTYPE html&gt;
&lt;html lang="fr"&gt;
    &lt;head&gt;
        &lt;title&gt;ReadyApp&lt;/title&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;!-- ============================================ --&gt;
        &lt;p&gt;Bonjour tout le monde&lt;/p&gt;
        &lt;!-- ============================================ --&gt;
    &lt;/body&gt;
&lt;/html&gt;</xmp></div></div><br><h3 class="Title8 GTitle3">Résultat</h3><br><div class="Img3 GImage"><img src="/Tutoriels/Web/HTML/img/i_html_minimal.png" alt="/Tutoriels/Web/HTML/img/i_html_minimal.png"></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Creer-un-element-xmp"><a class="Link9" href="#Fondamentaux">Créer un élément xmp</a></h2><br>L'élément HTML &lt;<b>xmp</b>&gt; (pour example) affiche le texte entre les balises d'ouverture et de fermeture sans interpréter le HTML qu'il contient et en utilisant une police à chasse fixe. La spécification HTML 2 recommande un affichage suffisamment large pour contenir 80 caractères par ligne.<br><br><h3 class="Title8 GTitle3">index.html</h3><br><div class="GCode1"><div class="Code2"><xmp class="AceCode" data-mode="html">&lt;!DOCTYPE html&gt;
&lt;html lang="fr"&gt;
    &lt;head&gt;
        &lt;title&gt;ReadyApp&lt;/title&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;!-- ============================================ --&gt;
        &lt;xmp&gt;
&lt;!DOCTYPE html&gt;
&lt;html lang="fr"&gt;
    &lt;head&gt;
        &lt;title&gt;ReadyApp&lt;/title&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;!-- ============================================ --&gt;
        &lt;p&gt;Bonjour tout le monde&lt;/p&gt;
        &lt;!-- ============================================ --&gt;
    &lt;/body&gt;
&lt;/html&gt;
        &lt;/xmp&gt;
        &lt;!-- ============================================ --&gt;
    &lt;/body&gt;
&lt;/html&gt;</xmp></div></div><br><h3 class="Title8 GTitle3">Résultat</h3><br><div class="Img3 GImage"><img src="/Tutoriels/Web/HTML/img/i_html_xmp.png" alt="/Tutoriels/Web/HTML/img/i_html_xmp.png"></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Creer-un-element-pre"><a class="Link9" href="#Fondamentaux">Créer un élément pre</a></h2><br>L'élément HTML &lt;pre&gt; représente du texte préformaté, généralement écrit avec une police à chasse fixe. Le texte est affiché tel quel, les espaces utilisés dans le document HTML seront retranscrits. Il est nécessaire d'échapper les caractères '&lt;' en &amp;lt; afin de s'assurer que le code écrit entre les éléments ne soit pas interprété de façon involontaire.<br><br><h3 class="Title8 GTitle3">index.html</h3><br><div class="GCode1"><div class="Code2"><xmp class="AceCode" data-mode="html">&lt;!DOCTYPE html&gt;
&lt;html lang="fr"&gt;
    &lt;head&gt;
        &lt;title&gt;ReadyApp&lt;/title&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;!-- ============================================ --&gt;
        &lt;pre&gt;
&lt;!DOCTYPE html&gt;
&lt;html lang="fr"&gt;
    &lt;head&gt;
        &lt;title&gt;ReadyApp&lt;/title&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;!-- ============================================ --&gt;
        &lt;p&gt;Bonjour tout le monde&lt;/p&gt;
        &lt;!-- ============================================ --&gt;
    &lt;/body&gt;
&lt;/html&gt;
        &lt;/pre&gt;
        &lt;!-- ============================================ --&gt;
    &lt;/body&gt;
&lt;/html&gt;</xmp></div></div><br><h3 class="Title8 GTitle3">Résultat</h3><br><div class="Img3 GImage"><img src="/Tutoriels/Web/HTML/img/i_html_pre.png" alt="/Tutoriels/Web/HTML/img/i_html_pre.png"></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Creer-un-element-code"><a class="Link9" href="#Fondamentaux">Créer un élément code</a></h2><br>L'élément HTML &lt;<b>code</b>&gt; représente un fragment de code machine. Par défaut, l'agent utilisateur utilise une police à chasse fixe (monospace) afin d'afficher le texte contenu dans cet élément.<br><br><h3 class="Title8 GTitle3">index.html</h3><br><div class="GCode1"><div class="Code2"><xmp class="AceCode" data-mode="html">&lt;!DOCTYPE html&gt;
&lt;html lang="fr"&gt;
    &lt;head&gt;
        &lt;title&gt;ReadyApp&lt;/title&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;!-- ============================================ --&gt;
        Calcul de la factorielle de &lt;code&gt;n&lt;/code&gt;.&lt;br&gt;
        Soit &lt;code&gt;f(x)&lt;/code&gt; ma fonction factorielle.&lt;br&gt;
        On a : &lt;code&gt;f(n) = n x f(n - 1)&lt;/code&gt;
        &lt;!-- ============================================ --&gt;
    &lt;/body&gt;
&lt;/html&gt;</xmp></div></div><br><h3 class="Title8 GTitle3">Résultat</h3><br><div class="Img3 GImage"><img src="/Tutoriels/Web/HTML/img/i_html_code.png" alt="/Tutoriels/Web/HTML/img/i_html_code.png"></div><br></div></div></div></div><br>