<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Contrôle de console à distance avec le SSH<br></div></a></div></div><div class="Body2 Orange"><br>Le but de ce tutoriel est de vous apprendre le contrôle de console à distance avec le <b>SSH</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div><br></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><br><b>SSH</b> est un protocole de communication sécurisé imposant un échange de clés de chiffrement en début de connexion pour ensuite authentifiés et chiffrés, tous les segments TCP échangés . Ce qui rend impossible l'utilisation d'un sniffer pour voir ce que fait l'utilisateur. Il a été conçu avec l'objectif de remplacer les différents protocoles non chiffrés comme rlogin, telnet, rcp et rsh.<br><br><div class="Img3 GImage"><img alt="/Tutoriels/Resources/SSH/img/b_ssh.png" class="lazy" data-src="/Tutoriels/Resources/SSH/img/b_ssh.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Installation"><a class="Link3" href="#">Installation</a></h1><div class="Body3"><br>Installer l'environnement SSH.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1619607054766"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1619607054766");</script></div><br><h2 class="Title7 GTitle2" id="Installation-1---Installation-sous-Mac"><a class="Link9" href="#Installation">1 - Installation sous Mac</a></h2><br><h2 class="Title7 GTitle2" id="Installation-1-1---Configurer-le-serveur-SSH"><a class="Link9" href="#Installation">1.1 - Configurer le serveur SSH</a></h2><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-mode="txt">Apple
Préférences Système
Partage
Cocher -&gt; Session à distance</pre></div></div><br><h2 class="Title7 GTitle2" id="Installation-1-2---Configurer-les-utilisateurs-accessibles"><a class="Link9" href="#Installation">1.2 - Configurer les utilisateurs accessibles</a></h2><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-mode="txt">Apple
Préférences Système
Partage
Autoriser l'accès pour
Cocher -&gt; Uniquement ses utilisateurs
Ajouter -&gt; imac</pre></div></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Zoc"><a class="Link3" href="#">Zoc</a></h1><div class="Body3"><br><b>Zoc</b> est un émulateur de terminal et de client Telnet pour les systèmes d'exploitation Windows et Mac supportant telnet , modem , SSH 1 et 2, RNIS , série , TAPI , Rlogin et d' autres moyens de communication. Son émulateur de terminal prend en charge l'émulation Xterm avec des couleurs complètes, méta-clés et impression locale, VT102 , VT220 et plusieurs types de ANSI , ainsi que Wyse , TVI , TN3270 et Sun CDE . Il prend en charge le remappage complet du clavier, la création de scripts dans REXX et d'autres langues, et la prise en charge des tubes nommés.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1619608517747"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1619608517747");</script></div><br><h2 class="Title7 GTitle2" id="Zoc-1---Installation"><a class="Link9" href="#Zoc">1 - Installation</a></h2><br><h2 class="Title7 GTitle2" id="Zoc-1-1---Installation-sous-Mac"><a class="Link9" href="#Zoc">1.1 - Installation sous Mac</a></h2><br><h2 class="Title7 GTitle2" id="Zoc-1-1-1---Telecharger-Zoc"><a class="Link9" href="#Zoc">1.1.1 - Télécharger Zoc</a></h2><br><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://www.emtec.com/download.html">https://www.emtec.com/download.html</a><br><br><b>zoc8023.dmg</b><br><br><h2 class="Title7 GTitle2" id="Zoc-1-1-2---Installer-Zoc"><a class="Link9" href="#Zoc">1.1.2 - Installer Zoc</a></h2><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-mode="txt">zoc8023.dmg
Langue -&gt; English
Agree
Zoc8 -&gt; Applications
Launchpad -&gt; Zoc8</pre></div></div><br><h2 class="Title7 GTitle2" id="Zoc-1-1-3---Demarrer-Zoc"><a class="Link9" href="#Zoc">1.1.3 - Démarrer Zoc</a></h2><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-mode="txt">Launchpad -&gt; Zoc8</pre></div></div><br><h2 class="Title7 GTitle2" id="Zoc-1-1-4---Supprimer-Zoc"><a class="Link9" href="#Zoc">1.1.4 - Supprimer Zoc</a></h2><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-mode="txt">Finder
Zoc8
Clic droit -&gt; Placer dans la corbeille</pre></div></div><br></div></div></div></div><br>