#!/bin/bash
#================================================
#export "PATH=.:$PATH"
#================================================
export "GPROJECT_ROOT=/home/pi/Programs/ReadyStudio"
export "GPROJECT_PATH=$GPROJECT_ROOT/ReadyDev"
export "GCMD_PATH=$GPROJECT_ROOT/ReadyDev/cmd/unix"
#================================================
