<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">ReadyTest</div></a></div></div><div class="Body2 Orange"><b>ReadyTest</b> est l'interface de Test des applications ReadyDev.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="List4 GSummary1"><div class="Item4"><span class="Icon10 fa fa-book"></span><a class="Link4" href="#Code">Code</a></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Code"><a class="Link3" href="#">Code</a></h1><div class="Body3">Le but de cette section est de tester l'insertion de code source.<br>Produit par <b>Gérard KESSE</b>.<br><br><h3 class="Title8 GTitle3">Code source (Ajouter)</h3><div class="GCode1"><pre><xmp class="Code2 prettyprint linenums">//===============================================
#include <iostream>
//===============================================
using namespace std;
//===============================================
int main(int argc, char** argv) {
    cout << "Bonjour tout le monde\n";
    return 0;
}
//===============================================</xmp></pre></div><br><h3 class="Title8 GTitle3">Code source (Supprimer)</h3><div class="Code2">//===============================================<br>#include&nbsp;&lt;iostream&gt;<br>//===============================================<br>using&nbsp;namespace&nbsp;std;<br>//===============================================<br>int&nbsp;main(int&nbsp;argc,&nbsp;char**&nbsp;argv)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;cout&nbsp;&lt;&lt;&nbsp;"Bonjour&nbsp;tout&nbsp;le&nbsp;monde\n";<br>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>}<br>//===============================================</div><br><h3 class="Title8 GTitle3">Code source (Dossier)</h3><br><div class="GCode2"><b>ReadyDev</b> met à votre disposition,<br>l'ensemble des codes sources abordés dans ce tutoriel.<br><br><div class="Body16"><div class="Row23" id="FilesystemMenu">...</div><div class="Row24" id="FilesystemList">...</div></div></div><script src="/js/class/GFilesystem.js"></script><script src="/js/filesystem.js"></script></div></div></div></div><br>