<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">ReadyTest</div></a></div></div><div class="Body2 Orange"><div class="Content0 GData1"><div class="Row0" id="Loader_1529080219033">Data 1 &gt; Test &gt; intro</div><script>loadData("Loader_1529080219033","Test","intro");</script></div><br><div class="List4 GSummary1"><div class="Item4"><span class="Icon10 fa fa-book"></span><a class="Link4" href="#Insertion de code source">Insertion de code source</a></div><div class="Item4"><span class="Icon10 fa fa-book"></span><a class="Link4" href="#Insertion de liste de données">Insertion de liste de données</a></div><div class="Item4"><span class="Icon10 fa fa-book"></span><a class="Link4" href="#Insertion de données">Insertion de données</a></div><div class="Item4"><span class="Icon10 fa fa-book"></span><a class="Link4" href="#Insertion effet parallax">Insertion effet parallax</a></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Insertion de code source"><a class="Link3" href="#">Insertion de code source</a></h1><div class="Body3">Le but de cette section est de tester <span class="GColor1" style="color: lime;">l'insertion de code source</span>.<br>Produit par <b>Gérard KESSE</b>.<br><br><h3 class="Title8 GTitle3">Code source (Ajouter)</h3><div class="GCode1"><pre><xmp class="Code2 prettyprint linenums">//===============================================
#include <iostream>
//===============================================
using namespace std;
//===============================================
int main(int argc, char** argv) {
    cout << "Bonjour tout le monde\n";
    return 0;
}
//===============================================</xmp></pre></div><br><h3 class="Title8 GTitle3">Code source (Dossier)</h3><br><div class="GCode2"><b>ReadyDev</b> met à votre disposition,<br>l'ensemble des codes sources abordés dans ce tutoriel.<br><br><div class="Body16"><div class="Row23" id="FilesystemMenu">...</div><div class="Row24" id="FilesystemList">...</div></div></div><script src="/js/class/GFilesystem.js"></script><script src="/js/filesystem.js"></script></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Insertion de liste de données"><a class="Link3" href="#">Insertion de liste de données</a></h1><div class="Body3">Le but de cette section est de tester <span class="GColor1" style="color: lime;">l'insertion d'une liste de données</span><br>stockées dans une base de données.<br>Produit par <b>Gérard KESSE</b>.<br><br><h3 class="Title8 GTitle3">Liste (Standard)</h3><br><div class="List4 GList1"><div class="Item4"><span class="Icon10 fa fa-book"></span><a class="Link4" href="/Tutoriels/Cpp/C/">Apprendre le C</a></div><div class="Item4"><span class="Icon10 fa fa-book"></span><a class="Link4" href="/Tutoriels/Cpp/Cpp/">Apprendre le C++</a></div><div class="Item4"><span class="Icon10 fa fa-book"></span><a class="Link4" href="/Tutoriels/Cpp/STL/">Apprendre la bibliothèque STL en C++</a></div></div><br><br><h3 class="Title8 GTitle3">Liste (Tableau)</h3><br><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Insertion de données"><a class="Link3" href="#">Insertion de données</a></h1><div class="Body3">Le but de cette section est de tester <span class="GColor1" style="color: lime;">l'insertion de données</span><br>stockées dans une base de données.<br>Produit par<b> Gérard KESSE</b>.<br><br><h3 class="Title8 GTitle3">Donnée (1 Clé)</h3><br><div class="Content0 GData1"><div class="Row0" id="Loader_1529079924085">Data 1 &gt; Test &gt; intro</div><script>loadData("Loader_1529079924085","Test","intro");</script></div></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Insertion effet parallax"><a class="Link3" href="#">Insertion effet parallax</a></h1><div class="Body3"><div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Ajouter un titre...</div></a></div></div><div class="Body2 Orange">Ajouter un texte...</div></div></div></div></div></div><br><br>