<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Créer un projet en Python</div></a></div></div><div class="Body2 Orange">Le but de ce tutoriel est de vous apprendre à créer un projet en <b>Python</b>.<br>Version Pro &amp; Industrielle. Produit par <b>Gérard KESSE</b>.<br>&nbsp;<br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><br><b>Python </b>est un langage de programmation interprété orienté objet, multiplateforme et doté d'un typage dynamique fort et d'une gestion automatique de la mémoire par ramasse-miettes.<br><br><div class="Img3 GImage"><img src="/Tutoriels/Python/img/b_cours_project.png" alt="/Tutoriels/Python/img/b_cours_project.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Créer un projet en Python"><a class="Link3" href="#">Créer un projet en Python</a></h1><div class="Body3"><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1599903147417"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1599903147417");</script></div><br><h2 class="Title7 GTitle2" id="Créer un projet en Python-Introduction"><a class="Link9" href="#Créer un projet en Python">Introduction</a></h2><br>Dans l'exemple qui suit, nous essayons de créer un projet en Python qui affiche un message à l'écran (Bonjour tout le monde).<br><br><h2 class="Title7 GTitle2" id="Créer un projet en Python-Programme principal"><a class="Link9" href="#Créer un projet en Python">Programme principal</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="python">#================================================
def main():
    print("Bonjour tout le monde")
#================================================
main()
#================================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un projet en Python-Fichier Makefile"><a class="Link9" href="#Créer un projet en Python">Fichier Makefile</a></h2><br><h3 class="Title8 GTitle3">Makefile.python.mak</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="makefile">GSRC = $(GPROJECT_SRC)
   
all: compile

compile:
	@python $(GSRC)\main.py $(argv)</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un projet en Python-Variables d'environnement"><a class="Link9" href="#Créer un projet en Python">Variables d'environnement</a></h2><br><h3 class="Title8 GTitle3">env.bat</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">::===============================================
set "PATH=C:\MinGW\bin;%PATH%"
set "PATH=C:\Python27;%PATH%"
::===============================================
set "GPROJECT_ROOT=C:\Users\Admin\Downloads\Programs"
set "GPROJECT_PATH=%GPROJECT_ROOT%\ReadyPython"
set "GPROJECT_SRC=%GPROJECT_PATH%\code\app\src"
::===============================================</xmp></pre></div><br><h3 class="Title8 GTitle3">make_p.bat</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">@echo off
::===============================================
set "args=%*"             
setlocal enabledelayedexpansion
set "lArgs=%*"             
set "lArgs=!lArgs:*%1 =!"  
endlocal && ( set "args=%lArgs%" )
::===============================================
mingw32-make -f Makefile.python.mak %1 argv="%args%"
::===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un projet en Python-Compilation automatique"><a class="Link9" href="#Créer un projet en Python">Compilation automatique</a></h2><br><h3 class="Title8 GTitle3">Terminal</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">make_p all</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un projet en Python-Compilation manuelle"><a class="Link9" href="#Créer un projet en Python">Compilation manuelle</a></h2><br><h3 class="Title8 GTitle3">Terminal</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">python main.py</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Créer un projet en Python-Résultat"><a class="Link9" href="#Créer un projet en Python">Résultat</a></h2><br><div class="Img3 GImage"><img src="/Tutoriels/Python/img/i_cours_project.png" alt="/Tutoriels/Python/img/i_cours_project.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Voir Aussi"><a class="Link3" href="#">Voir Aussi</a></h1><div class="Body3"><br>Dans cette même catégorie, vous pouvez consulter aussi :<br><br><span class="GColor1" style="color:lime;">Programmation de base</span><br><br><div class="Content0 GList1"><div class="Body0" id="Loader_1599902988430"><div class="Row26">List 1 &gt; Python &gt; basics</div></div><script>loadList1("Loader_1599902988430","Python","basics");</script></div><br></div></div></div></div><br>