<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Apprendre la programmation en C++<br></div></a></div></div><div class="Body2 Orange"><br>Le but de ce tutoriel est de vous apprendre la programmation en <b>C++</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div><br></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><b>C++</b> est un langage de programmation compilé permettant la programmation sous de multiples paradigmes (comme la programmation procédurale, orientée objet ou générique). Ses bonnes performances, et sa compatibilité avec le C en font un des langages de programmation les plus utilisés dans les applications où la performance est critique.<br><br><div class="Img3 GImage"><img src="/Tutoriels/Software_Development/Cpp/img/b_cpp.png" alt="/Tutoriels/Software_Development/Cpp/img/b_cpp.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Installation"><a class="Link3" href="#">Installation</a></h1><div class="Body3"><br>Installer l'environnement C++.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1616558777155"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1616558777155");</script></div><br><h2 class="Title7 GTitle2" id="Installation-1 - Installation sous Windows"><a class="Link9" href="#Installation">1 - Installation sous Windows</a></h2><br><h2 class="Title7 GTitle2" id="Installation-1.1 - MSYS2"><a class="Link9" href="#Installation">1.1 - MSYS2</a></h2><br>MSYS2 est un outil de développement de logiciels Linux sous Windows.<br><br><h2 class="Title7 GTitle2" id="Installation-1.1.1 - Installer MSYS2"><a class="Link9" href="#Installation">1.1.1 - Installer MSYS2</a></h2><br><h2 class="Title7 GTitle2" id="Installation-1.1.1.1 - Télécharger MSYS2"><a class="Link9" href="#Installation">1.1.1.1 - Télécharger MSYS2</a></h2><br><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20210228.exe">https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20210228.exe</a><br><br><h2 class="Title7 GTitle2" id="Installation-1.1.1.2 - Démarrer l'installation"><a class="Link9" href="#Installation">1.1.1.2 - Démarrer l'installation</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">msys2-x86_64-20210228.exe
Suivant
Dossier d'installation -> C:\msys64
Suivant
Raccourci du menu Démarrer -> MSYS2 64bit
Suivant
Suivant
Terminer</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Installation-1.1.2 - Démarrer MSYS2"><a class="Link9" href="#Installation">1.1.2 - Démarrer MSYS2</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Windows
MSYS2</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Installation-1.1.3 - Installer les packages"><a class="Link9" href="#Installation">1.1.3 - Installer les packages</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">pacman -Syu
pacman -S --needed -y make
pacman -S --needed -y gcc</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Tests"><a class="Link3" href="#">Tests</a></h1><div class="Body3"><br>Créer un projet C++.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1616682650861"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1616682650861");</script></div><br><h2 class="Title7 GTitle2" id="Tests-1 - Test sous Windows"><a class="Link9" href="#Tests">1 - Test sous Windows</a></h2><br><h2 class="Title7 GTitle2" id="Tests-1.1 - Test sous MSYS2"><a class="Link9" href="#Tests">1.1 - Test sous MSYS2</a></h2><br><h2 class="Title7 GTitle2" id="Tests-1.1.1 - Éditer le programme"><a class="Link9" href="#Tests">1.1.1 - Éditer le programme</a></h2><br><h3 class="Title8 GTitle3">main.cpp</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">//===============================================
#include &lt;iostream&gt;
//===============================================
int main(int argc, char** argv) {
    std::cout &lt;&lt; "Bonjour tout le monde\n";
    return 0;
}
//===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.1.2 - Compiler le projet"><a class="Link9" href="#Tests">1.1.2 - Compiler le projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">g++ -std=gnu++11 -c ./main.cpp -o ./main.o</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.1.3 - Éditer les liens du projet"><a class="Link9" href="#Tests">1.1.3 - Éditer les liens du projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">g++ -std=gnu++11 -o ./rdcpp.exe ./main.o</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.1.4 - Exécuter le projet"><a class="Link9" href="#Tests">1.1.4 - Exécuter le projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">./rdcpp.exe</xmp></pre></div><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">Bonjour tout le monde</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Git"><a class="Link3" href="#">Git</a></h1><div class="Body3"><br>Git est outil de gestion de versions décentralisée.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1616679343643"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1616679343643");</script></div><br><h2 class="Title7 GTitle2" id="Git-1 - Installation"><a class="Link9" href="#Git">1 - Installation</a></h2><br><h2 class="Title7 GTitle2" id="Git-1.1 - Installation sous Windows"><a class="Link9" href="#Git">1.1 - Installation sous Windows</a></h2><br><h2 class="Title7 GTitle2" id="Git-1.1.1 - Installation sous MSYS2"><a class="Link9" href="#Git">1.1.1 - Installation sous MSYS2</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">pacman -S --needed git
pacman -S --needed vim</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Git-2 - Utilisations"><a class="Link9" href="#Git">2 - Utilisations</a></h2><br><h2 class="Title7 GTitle2" id="Git-2.1 - Configurations"><a class="Link9" href="#Git">2.1 - Configurations</a></h2><br><h2 class="Title7 GTitle2" id="Git-2.1.1 - Configurer l'environnement de l'utilisateur"><a class="Link9" href="#Git">2.1.1 - Configurer l'environnement de l'utilisateur</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">git config --global user.name "Gerard KESSE"
git config --global user.email "tiakagerardhotmail.com"
git config --global core.editor "vim"
git config --list</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Git-2.1.2 - Configurer la sauvegarde des identifiants"><a class="Link9" href="#Git">2.1.2 - Configurer la sauvegarde des identifiants</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">git config credential.helper store</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Git-2.2 - Opérations"><a class="Link9" href="#Git">2.2 - Opérations</a></h2><br><h2 class="Title7 GTitle2" id="Git-2.2.1 - Préparer un dépôt Git"><a class="Link9" href="#Git">2.2.1 - Préparer un dépôt Git</a></h2><br><h2 class="Title7 GTitle2" id="Git-2.2.1.1 - Créer un dépôt Git"><a class="Link9" href="#Git">2.2.1.1 - Créer un dépôt Git</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">git init</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Git-2.2.1.2 - Cloner un dépôt Git"><a class="Link9" href="#Git">2.2.1.2 - Cloner un dépôt Git</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">cd $GPROJECT_ROOT
git clone $GGIT_URL $GGIT_NAME</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Git-2.2.2 - Pousser un dépôt Git"><a class="Link9" href="#Git">2.2.2 - Pousser un dépôt Git</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">cd $GPROJECT_PATH
git add --all
git commit -m "Initial Commit"
git push -u origin master</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Git-2.2.3 - Tirer un dépôt Git"><a class="Link9" href="#Git">2.2.3 - Tirer un dépôt Git</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">git pull</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Bibliothèques"><a class="Link3" href="#">Bibliothèques</a></h1><div class="Body3"><br><span class="GColor1" style="color:lime;">Blibliothèques C++</span><br><br><div class="Content0 GList1"><div class="Body0" id="Loader_1616786029007"><div class="Row26">List 1 &gt; Cpp &gt; libs</div></div><script>loadList1("Loader_1616786029007","Cpp","libs");</script></div><br></div></div></div></div><br>