<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Appel de bibliothèques natives C/C++ avec JNI en Java<br></div></a></div></div><div class="Body2 Orange"><br>Le but de ce tutoriel est de vous apprendre à appeler des bibliothèques natives C/C++ avec <b>JNI </b>en <b>Java</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div><br></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><br><b>JNI </b>est une bibliothèque logicielle d'interfaçage, intégrée nativement au JDK de Java, qui permet au code Java s'exécutant à l'intérieur de la JVM d'appeler et d'être appelé par des applications natives basées sur des langages tels que le C, C++, assembleur, etc.<br><br><div class="Img3 GImage"><img src="/Tutoriels/Software_Development/Java/img/b_jni.png" alt="/Tutoriels/Software_Development/Java/img/b_jni.png"></div><br><h2 class="Title7 GTitle2" id="Introduction-Prérequis"><a class="Link9" href="#Introduction">Prérequis</a></h2><br>$\checkmark$ <a class="Link7 GLink1" style="color:lime;" href="../#Installation">Installer l'environnement Java</a><br>$\checkmark$ <a class="Link7 GLink1" style="color:lime;" href="../../C0/#Installation">Installer l'environnement C</a><br>$\checkmark$ <a class="Link7 GLink1" style="color:lime;" href="../../Cpp/#Installation">Installer l'environnement C++</a><br><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Installation"><a class="Link3" href="#">Installation</a></h1><div class="Body3"><br>Installer l'environnement JNI pour Java.<br><br>Aucune installation n'est nécessaire.<br><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Tests"><a class="Link3" href="#">Tests</a></h1><div class="Body3"><br>Créer un projet JNI en Java.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1617359571081"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1617359571081");</script></div><br><h2 class="Title7 GTitle2" id="Tests-1 - Test sous Ubuntu"><a class="Link9" href="#Tests">1 - Test sous Ubuntu</a></h2><br><h2 class="Title7 GTitle2" id="Tests-1.1 - Test sous C"><a class="Link9" href="#Tests">1.1 - Test sous C</a></h2><br><h2 class="Title7 GTitle2" id="Tests-1.1.1 - Editer le programme Java"><a class="Link9" href="#Tests">1.1.1 - Editer le programme Java</a></h2><br><h3 class="Title8 GTitle3">GMain.java</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="java">//===============================================
package com.pkg.readyc;
//===============================================
public class GMain {
    //===============================================
    static {
        System.loadLibrary("rdc");
    }
    //===============================================
    public static void main(String[] args){
        new GMain().sayHello();
    }
    //===============================================
    private native void sayHello();
    //===============================================
}
//===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.1.2 - Générer le fichier header"><a class="Link9" href="#Tests">1.1.2 - Générer le fichier header</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">javac -h . com/pkg/readyc/GMain.java</xmp></pre></div><br><h3 class="Title8 GTitle3">com_pkg_readyc_GMain.h</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">/* DO NOT EDIT THIS FILE - it is machine generated */
#include &lt;jni.h&gt;
/* Header for class com_pkg_readyc_GMain */

#ifndef _Included_com_pkg_readyc_GMain
#define _Included_com_pkg_readyc_GMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pkg_readyc_GMain
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pkg_readyc_GMain_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif</xmp></pre></div><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">cp -f com_pkg_readyc_GMain.h com_pkg_readyc_GMain.c</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.1.3 - Editer le programme C"><a class="Link9" href="#Tests">1.1.3 - Editer le programme C</a></h2><br><h3 class="Title8 GTitle3">com_pkg_readyc_GMain.c</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">//===============================================
#include "com_pkg_readyc_GMain.h"
//===============================================
#include &lt;stdio.h&gt;
//===============================================
JNIEXPORT void JNICALL 
Java_com_pkg_readyc_GMain_sayHello(JNIEnv *env, jobject obj) {
    printf("[C] Bonjour tout le monde\n");
    return;
}
//===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.1.4 - Compiler le programme C"><a class="Link9" href="#Tests">1.1.4 - Compiler le programme C</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">gcc -std=gnu11 \
-c com_pkg_readyc_GMain.c \
-o com_pkg_readyc_GMain.o \
-I/usr/lib/jvm/java-15-openjdk-arm64/include \
-I/usr/lib/jvm/java-15-openjdk-arm64/include/linux</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.1.5 - Créer la librairie dynamique C"><a class="Link9" href="#Tests">1.1.5 - Créer la librairie dynamique C</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">gcc -shared -fPIC -o librdc.so \
com_pkg_readyc_GMain.o</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.1.6 - Exécuter le projet"><a class="Link9" href="#Tests">1.1.6 - Exécuter le projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">java com.pkg.readyc.GMain</xmp></pre></div><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">[C] Bonjour tout le monde</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.2 - Test sous C++"><a class="Link9" href="#Tests">1.2 - Test sous C++</a></h2><br><h2 class="Title7 GTitle2" id="Tests-1.2.1 - Éditer le programme Java"><a class="Link9" href="#Tests">1.2.1 - Éditer le programme Java</a></h2><br><h3 class="Title8 GTitle3">GMain.java</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="java">//===============================================
package com.pkg.readycpp;
//===============================================
public class GMain {
    //===============================================
    static {
        System.loadLibrary("rdcpp");
    }
    //===============================================
    public static void main(String[] args){
        new GMain().sayHello();
    }
    //===============================================
    private native void sayHello();
    //===============================================
}
//===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.2.2 - Générer le fichier header"><a class="Link9" href="#Tests">1.2.2 - Générer le fichier header</a></h2><br><h3 class="Title8 GTitle3">com_pkg_readycpp_GMain.h</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">/* DO NOT EDIT THIS FILE - it is machine generated */
#include &lt;jni.h&gt;
/* Header for class com_pkg_readycpp_GMain */

#ifndef _Included_com_pkg_readycpp_GMain
#define _Included_com_pkg_readycpp_GMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pkg_readycpp_GMain
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pkg_readycpp_GMain_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif</xmp></pre></div><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">cp -f com_pkg_readycpp_GMain.h com_pkg_readycpp_GMain.cpp</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.2.3 - Editer le programme C++"><a class="Link9" href="#Tests">1.2.3 - Editer le programme C++</a></h2><br><h3 class="Title8 GTitle3">com_pkg_readycpp_GMain.cpp</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">//===============================================
#include "com_pkg_readycpp_GMain.h"
//===============================================
#include &lt;iostream&gt;
//===============================================
JNIEXPORT void JNICALL 
Java_com_pkg_readycpp_GMain_sayHello(JNIEnv *env, jobject obj) {
    std::cout &lt;&lt; "[C++] Bonjour tout le monde\n";
    return;
}
//===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.2.4 - Compiler le programme C++"><a class="Link9" href="#Tests">1.2.4 - Compiler le programme C++</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">g++ -std=gnu++11 \
-c com_pkg_readycpp_GMain.cpp \
-o com_pkg_readycpp_GMain.o \
-I/usr/lib/jvm/java-15-openjdk-arm64/include \
-I/usr/lib/jvm/java-15-openjdk-arm64/include/linux</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.2.5 - Créer la librairie dynamique C++"><a class="Link9" href="#Tests">1.2.5 - Créer la librairie dynamique C++</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">g++ -shared -fPIC -o librdcpp.so \
com_pkg_readycpp_GMain.o</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.2.6 - Exécuter le projet"><a class="Link9" href="#Tests">1.2.6 - Exécuter le projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">java com.pkg.readycpp.GMain</xmp></pre></div><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">[C++] Bonjour tout le monde</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Voir Aussi"><a class="Link3" href="#">Voir Aussi</a></h1><div class="Body3"><br><span class="GColor1" style="color:lime;">Bibliothèques Java</span><br><br><div class="Content0 GList1"><div class="Body0" id="Loader_1617359532864"><div class="Row26">List 1 &gt; Java &gt; libs</div></div><script>loadList1("Loader_1617359532864","Java","libs");</script></div><br></div></div></div></div><br>