<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Apprendre la gestion de version avec Git</div></a></div></div><div class="Body2 Orange"><b>Git</b> est un système de gestion de versions.<br>Le but de ce tutoriel est de vous apprendre la gestion de versions avec <b>Git</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Installation sous Linux"><a class="Link3" href="#">Installation sous Linux</a></h1><div class="Body3">Le but de cette section est de vous présenter les différents outils nécessaires pour apprendre la gestion de versions avec <span class="GColor1" style="color:lime;">Git</span><span class="GColor1" style="color:lime;"></span>, sous Linux.<br>Produit par <b>Gérard KESSE</b>.<br><br>Dans ce tutoriel, nous utiliserons, sous Linux:<br>- Git, comme système de gestion de versions.<br>- GitHub, comme serveur de données Git.<br>- Notepad++, comme éditeur de texte.<br><br><h3 class="Title8 GTitle3">Télécharger Git</h3><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://git-scm.com/downloads">https://git-scm.com/downloads</a><br><br><h3 class="Title8 GTitle3">Accéder à GitHub</h3><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://github.com/">https://github.com/</a><br><br><h3 class="Title8 GTitle3">Télécharger Notepad++</h3><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://notepad-plus-plus.org/">https://notepad-plus-plus.org/</a><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Créer un dépôt"><a class="Link3" href="#">Créer un dépôt</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Créer un dépôt </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576521311119"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576521311119");</script></div><br><h2 class="Title7 GTitle2" id="Créer un dépôt-Créer le dépôt"><a class="Link9" href="#Créer un dépôt">Créer le dépôt</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GDEPOT=/home/centos/Programs/ReadyGit/depot
mkdir -p $GDEPOT
cd $GDEPOT
git init --bare --shared</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Initialiser un projet"><a class="Link3" href="#">Initialiser un projet</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Initialiser un projet </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576538715900"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576538715900");</script></div><br><h2 class="Title7 GTitle2" id="Initialiser un projet-Initialiser le projet"><a class="Link9" href="#Initialiser un projet">Initialiser le projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
mkdir -p $GPROJECT
cd $GPROJECT
git init</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Ajouter un dépôt"><a class="Link3" href="#">Ajouter un dépôt</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Ajouter un dépôt </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576539384551"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576539384551");</script></div><br><h2 class="Title7 GTitle2" id="Ajouter un dépôt-Ajouter le dépôt"><a class="Link9" href="#Ajouter un dépôt">Ajouter le dépôt</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
GDEPOT=file:////home/centos/Programs/ReadyGit/depot
cd $GPROJECT
git remote add origin $GDEPOT</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Afficher les dépôts"><a class="Link3" href="#">Afficher les dépôts</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Afficher les dépôts </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576540413669"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576540413669");</script></div><br><h2 class="Title7 GTitle2" id="Afficher les dépôts-Afficher les dépôts"><a class="Link9" href="#Afficher les dépôts">Afficher les dépôts</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git remote -v</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Ajouter un fichier"><a class="Link3" href="#">Ajouter un fichier</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Ajouter un fichier </span>avec Git.<br><br>Pour étayer cette section, nous allaons créer un fichier <span class="GColor1" style="color:teal;">README.md</span>.<br>Le fichier <span class="GColor1" style="color:teal;">README.md</span> contiendra des informations sur le but de notre projet.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576547735514"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576547735514");</script></div><br><h2 class="Title7 GTitle2" id="Ajouter un fichier-Ajouter le fichier"><a class="Link9" href="#Ajouter un fichier">Ajouter le fichier</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
nano README.md
</xmp></pre></div><br><h3 class="Title8 GTitle3">Fichier README (README.md)</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh"># ReadyGit
ReadyGit est un tutoriel pour apprendre à utiliser Git.
</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Afficher le status d'un projet"><a class="Link3" href="#">Afficher le status d'un projet</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Afficher le status d'un projet </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576548276862"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576548276862");</script></div><br><h2 class="Title7 GTitle2" id="Afficher le status d'un projet-Afficher le status de projet"><a class="Link9" href="#Afficher le status d'un projet">Afficher le status de projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git status</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Indexer un fichier"><a class="Link3" href="#">Indexer un fichier</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Indexer un fichier </span>avec Git.<br><br>Pour étayer cette section, nous allons indexer le fichier README.md.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576548534834"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576548534834");</script></div><br><h2 class="Title7 GTitle2" id="Indexer un fichier-Indexer le fichier"><a class="Link9" href="#Indexer un fichier">Indexer le fichier</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git add README.md</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Valider les modifications d'un projet"><a class="Link3" href="#">Valider les modifications d'un projet</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Valider les modifications d'un projet </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576549101833"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576549101833");</script></div><br><h2 class="Title7 GTitle2" id="Valider les modifications d'un projet-Valider les modifications du projet"><a class="Link9" href="#Valider les modifications d'un projet">Valider les modifications du projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git commit -m "Initial Commit"</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Pousser les modifications d'un projet"><a class="Link3" href="#">Pousser les modifications d'un projet</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Pousser les modifications d'un projet </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576549269950"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576549269950");</script></div><br><h2 class="Title7 GTitle2" id="Pousser les modifications d'un projet-Pousser les modifications du projet"><a class="Link9" href="#Pousser les modifications d'un projet">Pousser les modifications du projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git push origin master</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Créer une branche"><a class="Link3" href="#">Créer une branche</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Créer une branche </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576549801995"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576549801995");</script></div><br><h2 class="Title7 GTitle2" id="Créer une branche-Créer la branche"><a class="Link9" href="#Créer une branche">Créer la branche</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git branch develop
</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Afficher les branches"><a class="Link3" href="#">Afficher les branches</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Afficher les branches </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576550410263"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576550410263");</script></div><br><h2 class="Title7 GTitle2" id="Afficher les branches-Afficher les branches"><a class="Link9" href="#Afficher les branches">Afficher les branches</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git branch</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Basculer sur une branche"><a class="Link3" href="#">Basculer sur une branche</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Basculer sur une branche </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576550414434"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576550414434");</script></div><br><h2 class="Title7 GTitle2" id="Basculer sur une branche-Basculer sur la branche"><a class="Link9" href="#Basculer sur une branche">Basculer sur la branche</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git checkout develop</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Ajouter du contenu"><a class="Link3" href="#">Ajouter du contenu</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Ajouter du contenu </span>avec Git.<br><br>Pour étayer cette section, nous allons créer un programme C, avec l'IDE Eclipse.<br>Le programme C affichera <span class="GColor1" style="color:teal;">Bonjour tout le monde</span> dans la console.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576543275809"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576543275809");</script></div><br><h2 class="Title7 GTitle2" id="Ajouter du contenu-Programme principal"><a class="Link9" href="#Ajouter du contenu">Programme principal</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
GSRC=$GPROJECT/code/GProject/src
mkdir -p $GSRC
cd $GSRC
nano main.c</xmp></pre></div><br><h3 class="Title8 GTitle3">Programme principal (main.c)</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="c_cpp">//===============================================
#include &lt;stdio.h&gt;
//===============================================
int main(int argc, char** argv) {
	printf("Bonjour tout le monde\n");
	return 0;
}
//===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Ajouter du contenu-Fichier Makefile"><a class="Link9" href="#Ajouter du contenu">Fichier Makefile</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
GUNIX=$GPROJECT/unix
mkdir -p $GUNIX
cd $GUNIX
nano Makefile</xmp></pre></div><br><h3 class="Title8 GTitle3">Fichier Makefile (Makefile)</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="Makefile">GSRC = ../code/GProject/src
GBIN = bin
GBUILD = build
GTARGET = $(GBIN)/GProject.exe 

GINCS = \

GLIBS = \

GOBJS = \
    $(patsubst $(GSRC)/%.c, $(GBUILD)/%.o, $(wildcard $(GSRC)/*.c)) \

GCFLAGS = \
    -std=c11 \
    
all: $(GOBJS)
	@mkdir -p $(GBIN)
	gcc -o $(GTARGET) $(GOBJS) $(GLIBS) 
$(GBUILD)/%.o: $(GSRC)/%.c
	@mkdir -p $(GBUILD)
	gcc $(GCFLAGS) -c $&lt; -o $@ $(GINCS)
clean:
	rm -f $(GBUILD)/*.o $(GBIN)/*.exe</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Ajouter du contenu-Compiler le programme"><a class="Link9" href="#Ajouter du contenu">Compiler le programme</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
GUNIX=$GPROJECT/unix
cd $GUNIX
make</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Ajouter du contenu-Exécuter le programme"><a class="Link9" href="#Ajouter du contenu">Exécuter le programme</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
GUNIX=$GPROJECT/unix
cd $GUNIX
./bin/GProject.exe</xmp></pre></div><br><div class="Img3 GImage"><img src="img/Programme.png" alt="img/Programme.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Indexer tous les fichiers"><a class="Link3" href="#">Indexer tous les fichiers</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Indexer tous les fichiers </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576562400049"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576562400049");</script></div><br><h2 class="Title7 GTitle2" id="Indexer tous les fichiers-Indexer tous les fichiers"><a class="Link9" href="#Indexer tous les fichiers">Indexer tous les fichiers</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git add --all</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Supprimer des fichiers indexés"><a class="Link3" href="#">Supprimer des fichiers indexés</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Supprimer des fichiers indexés </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576564340015"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576564340015");</script></div><br><h2 class="Title7 GTitle2" id="Supprimer des fichiers indexés-Supprimer les fichiers indexés"><a class="Link9" href="#Supprimer des fichiers indexés">Supprimer les fichiers indexés</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git rm -f code/.gitignore
git rm -f code/GProject/.gitignore</xmp></pre></div></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Désindexer des fichiers"><a class="Link3" href="#">Désindexer des fichiers</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Désindexer des fichiers </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576563310276"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576563310276");</script></div><br><h2 class="Title7 GTitle2" id="Désindexer des fichiers-Désindexer les fichiers"><a class="Link9" href="#Désindexer des fichiers">Désindexer les fichiers</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git reset HEAD code/GProject/.cproject
git reset HEAD code/GProject/.project
git reset HEAD code/GProject/.settings
git reset HEAD unix/bin
git reset HEAD unix/build</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Ignorer des fichiers"><a class="Link3" href="#">Ignorer des fichiers</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Ignorer des fichiers </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576564679043"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576564679043");</script></div><br><h2 class="Title7 GTitle2" id="Ignorer des fichiers-Ignorer les fichiers"><a class="Link9" href="#Ignorer des fichiers">Ignorer les fichiers</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
nano .gitignore</xmp></pre></div><br><h3 class="Title8 GTitle3">Fichier gitignore (.gitignore)</h3><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">#================================================
# Makefile
#================================================
/**/bin/
/**/build/

#================================================
# Eclipse
#================================================
/**/Release/
/**/Debug/
/**/.metadata/
/**/.settings/
/**/.project
/**/.cproject</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Pousser des modifications sur une branche"><a class="Link3" href="#">Pousser des modifications sur une branche</a></h1><div class="Body3">Le but de cette section est de vous apprendre à <span class="GColor1" style="color:lime;">Pousser des modifications sur une branche </span>avec Git.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1576565246829"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1576565246829");</script></div><br><h2 class="Title7 GTitle2" id="Pousser des modifications sur une branche-Basculer sur la branche"><a class="Link9" href="#Pousser des modifications sur une branche">Basculer sur la branche</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git checkout develop</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Pousser des modifications sur une branche-Indexer toutes les modifications"><a class="Link9" href="#Pousser des modifications sur une branche">Indexer toutes les modifications</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git add --all</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Pousser des modifications sur une branche-Valider les modifications"><a class="Link9" href="#Pousser des modifications sur une branche">Valider les modifications</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git commit -m "developpement du systeme d'affichage"</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Pousser des modifications sur une branche-Pousser les modifications sur la branche"><a class="Link9" href="#Pousser des modifications sur une branche">Pousser les modifications sur la branche</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">GPROJECT=/home/centos/Programs/ReadyGit/projet
cd $GPROJECT
git push origin develop</xmp></pre></div><br></div></div></div></div><br>