<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Création d'interfaces homme-machine avec Qt en Go<br></div></a></div></div><div class="Body2 Orange"><br>Le but de ce tutoriel est de vous apprendre la création d'interfaces homme-machine avec <b>Qt </b>en <b>Go</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div><br></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><br><b>Qt </b>est une bibliothèque de composants d'interfaces graphiques (widgets), d'accès aux données, de connexions réseaux, de gestion des fils d'exécution, d'analyse XML, etc, et doté d'un mécanisme de notifications par des signaux et slots.<br><br><div class="Img3 GImage"><img src="/Tutoriels/Software_Development/Go/img/b_qt.png" alt="/Tutoriels/Software_Development/Go/img/b_qt.png"></div><br><h2 class="Title7 GTitle2" id="Introduction-Prérequis"><a class="Link9" href="#Introduction">Prérequis</a></h2><br>$\checkmark$ <a class="Link7 GLink1" style="color:lime;" href="../#Installation">Installer l'environnement Go</a><br>$\checkmark$ <a class="Link7 GLink1" style="color:lime;" href="../../../Version_Control/Git/#Installation">Installer l'environnement Git</a><br><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Installation"><a class="Link3" href="#">Installation</a></h1><div class="Body3"><br>Installer l'environnement Qt.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1616688816465"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1616688816465");</script></div><br><h2 class="Title7 GTitle2" id="Installation-1 - Installation sous Windows"><a class="Link9" href="#Installation">1 - Installation sous Windows</a></h2><br><h2 class="Title7 GTitle2" id="Installation-1.1 - Installation sous Batch"><a class="Link9" href="#Installation">1.1 - Installation sous Batch</a></h2><br><h2 class="Title7 GTitle2" id="Installation-1.1.1 - Choisir un répertoire de projet"><a class="Link9" href="#Installation">1.1.1 - Choisir un répertoire de projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">REPERTOIRE_PROJET   -&gt; ReadyTest\go\qt\
REPERTOIRE_SOURCE   -&gt; ReadyTest\go\qt\code\
PROGRAMME_PRINCIPAL -&gt; ReadyTest\go\qt\code\main.go</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Installation-1.1.2 - Initialiser le répertoire de projet"><a class="Link9" href="#Installation">1.1.2 - Initialiser le répertoire de projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">set "GOPATH=C:\Users\Admin\Downloads\Programs\ReadyTest\go\qt"</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Installation-1.1.3 - Télécharger la bibliothèque Qt"><a class="Link9" href="#Installation">1.1.3 - Télécharger la bibliothèque Qt</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="batchfile">go get github.com/therecipe/qt</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Tests"><a class="Link3" href="#">Tests</a></h1><div class="Body3"><br>Créer un projet Qt en Go.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1616705914360"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1616705914360");</script></div><br><h2 class="Title7 GTitle2" id="Tests-1 - Test sous Windows"><a class="Link9" href="#Tests">1 - Test sous Windows</a></h2><br><h2 class="Title7 GTitle2" id="Tests-1.1 - Test sous Batch"><a class="Link9" href="#Tests">1.1 - Test sous Batch</a></h2><br><h2 class="Title7 GTitle2" id="Tests-1.1.1 - Éditer le programme"><a class="Link9" href="#Tests">1.1.1 - Éditer le programme</a></h2><br><h3 class="Title8 GTitle3">main.go</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="golang">//===============================================
package main
//===============================================
import "os"
import "github.com/therecipe/qt/widgets"
import "github.com/therecipe/qt/core"
//===============================================
func main() {
    lApp := widgets.NewQApplication(len(os.Args), os.Args)
    lLabel := widgets.NewQLabel(nil, 0)
    lLabel.SetText("Bonjour tout le monde")
    lLabel.SetAlignment(core.Qt__AlignCenter)
    lLabel.QWidget_PTR().Resize2(500, 250)
    lLabel.QWidget_PTR().SetWindowTitle("ReadyApp")
    lLabel.QWidget_PTR().Show()
    lApp.Exec()
}
//===============================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.1.2 - Compiler projet"><a class="Link9" href="#Tests">1.1.2 - Compiler projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">go build -o rdqt.exe main.go</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.1.3 - Exécuter le projet"><a class="Link9" href="#Tests">1.1.3 - Exécuter le projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">rdqt.exe</xmp></pre></div><br><div class="Img3 GImage"><img src="/Tutoriels/Software_Development/Cpp/img/i_qt_test.png" alt="/Tutoriels/Software_Development/Cpp/img/i_qt_test.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Voir Aussi"><a class="Link3" href="#">Voir Aussi</a></h1><div class="Body3"><br>Dans cette même catégorie, vous pouvez consulter aussi :<br><br><span class="GColor1" style="color:lime;">Bibliothèques Go</span><br><br><div class="Content0 GList1"><div class="Body0" id="Loader_1617495176526"><div class="Row26">List 1 &gt; Go &gt; libs</div></div><script>loadList1("Loader_1617495176526","Go","libs");</script></div><br></div></div></div></div><br>