<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">onfigurations avec le RaspberryPi</div></a></div></div><div class="Body2 Orange">Le but de ce tutoriel est de vous apprendre à gérer une diode LED en C avec le <b>RaspberryPi</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3">Un <b>système embarqué</b> est un système électronique et informatique autonome, souvent temps réel, spécialisé dans une tâche précise et dont les ressources sont généralement limitées spatialement (encombrement réduit) et énergétiquement (consommation restreinte).<br><br><div class="Img3 GImage"><img src="/Tutoriels/Embedded_System/img/b_raspberrypi_environment.png" alt="/Tutoriels/Embedded_System/img/b_raspberrypi_environment.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Configurations avec Xenomai"><a class="Link3" href="#">Configurations avec Xenomai</a></h1><div class="Body3"><br>Xenomai est un module permettant d'apporter des fonctionnalités temps réel à un noyau Linux standard.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1614775778507"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1614775778507");</script></div><br><h2 class="Title7 GTitle2" id="Configurations avec Xenomai-Télécharger Xenomai"><a class="Link9" href="#Configurations avec Xenomai">Télécharger Xenomai</a></h2><br>On télécharge les sources de Xenomai.<br><br><h3 class="Title8 GTitle3">Terminal</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">wget https://xenomai.org/downloads/xenomai/stable/xenomai-3.1.tar.bz2
tar xjfv xenomai-3.1.tar.bz2
rm -f xenomai-3.1.tar.bz2</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Configuration avec Linux Kernel"><a class="Link3" href="#">Configuration avec Linux Kernel</a></h1><div class="Body3"><br>Linux Kernel est le noyau Linux qui contient toutes les fonctionnalités d'une distribution Linux.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1614782370020"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1614782370020");</script></div><br><h2 class="Title7 GTitle2" id="Configuration avec Linux Kernel-Télécharger le noyau Linux"><a class="Link9" href="#Configuration avec Linux Kernel">Télécharger le noyau Linux</a></h2><br>On télécharge les sources du noyau Linux.<br><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">wget https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/linux-5.11.tar.gz
tar xzfv linux-5.11.tar.gz
rm -f linux-5.11.tar.gz</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Configuration avec Linux Kernel-Télécharger le patch du noyau Linux"><a class="Link9" href="#Configuration avec Linux Kernel">Télécharger le patch du noyau Linux</a></h2><br>Le patch du noyau Linux contient l'ensemble des correctifs associé au noyau Linux.<br>On télécharge le patch associé au noyau Linux.<br><br><h3 class="Title8 GTitle3">Terminal</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">wget https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/patch-5.11.2.xz</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Configuration avec Linux Kernel-Appliquer le patch au noyau Linux"><a class="Link9" href="#Configuration avec Linux Kernel">Appliquer le patch au noyau Linux</a></h2><br>On applique le patch associé au noyau Linux.<br><br><h3 class="Title8 GTitle3">Terminal</h3><br><br><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Comprendre le concept des patchs"><a class="Link3" href="#">Comprendre le concept des patchs</a></h1><div class="Body3"><br>Un patch est ensemble de correctifs associé à un module à une version donnée.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1614788582368"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1614788582368");</script></div><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-Cas 1 : Patch à partir du répertoire courant"><a class="Link9" href="#Comprendre le concept des patchs">Cas 1 : Patch à partir du répertoire courant</a></h2><br>On décide de créer un patch à partir du répertoire courant.<br><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-1.1 - Créer un module à la version v1.0"><a class="Link9" href="#Comprendre le concept des patchs">1.1 - Créer un module à la version v1.0</a></h2><br>On crée un module à la version v1.0.<br><br><h3 class="Title8 GTitle3">module_setup_v1.0</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">10 + 10 = 20
10 + 30 = 40
10 + 60 = 50</xmp></pre></div><br>Après la révision du module à la version v1.0, on remarque une erreur à ligne (3).<br>On note l'erreur : <span class="GColor1" style="color:gray;">10 + 60 = 50</span><br>On définit le correctif : <span class="GColor1" style="color:teal;">10 + 60 = 70</span><br><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-1.2 - Créer un correctif à la version v1.0.1"><a class="Link9" href="#Comprendre le concept des patchs">1.2 - Créer un correctif à la version v1.0.1</a></h2><br>On crée un correctif à la version v1.0.1.<br><br><h3 class="Title8 GTitle3">module_setup_v1.0.1</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">10 + 10 = 20
10 + 30 = 40
10 + 60 = 70</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-1.3 - Créer le path à la version v1.0"><a class="Link9" href="#Comprendre le concept des patchs">1.3 - Créer le path à la version v1.0</a></h2><br>On crée un patch à la version v1.0 entre deux fichiers.<br><br><h3 class="Title8 GTitle3">Terminal</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">diff -u module_setup_v1.0 module_setup_v1.0.1 &gt; module_patch_v1.0.patch</xmp></pre></div><br><h3 class="Title8 GTitle3">module_patch_v1.0.patch</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">--- module_setup_v1.0   2021-03-03 11:13:11.566919552 -0500
+++ module_setup_v1.0.1 2021-03-03 11:14:45.882919552 -0500
@@ -1,4 +1,4 @@
 10 + 10 = 20
 10 + 30 = 40
-10 + 60 = 50
+10 + 60 = 70</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-1.4 - Appliquer le patch à la version v1.0"><a class="Link9" href="#Comprendre le concept des patchs">1.4 - Appliquer le patch à la version v1.0</a></h2><br>On applique le patch à la version v1.0 à partir du répertoire courant.<br><br><h3 class="Title8 GTitle3">Terminal</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">patch -p0 &lt; module_patch_v1.0.patch</xmp></pre></div><br><h3 class="Title8 GTitle3">Terminal (Output)<br></h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">patching file module_setup_v1.0</xmp></pre></div><br><h3 class="Title8 GTitle3">module_setup_v1.0</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">10 + 10 = 20
10 + 30 = 40
10 + 60 = 70</xmp></pre></div><br>On remarque que le patch s'est appliqué avec succès.<br>Le correctif a bien été installé.<br><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-1.5 - Réappliquer le patch à la version v1.0"><a class="Link9" href="#Comprendre le concept des patchs">1.5 - Réappliquer le patch à la version v1.0</a></h2><br>On tente de réappliquer le patch à la version v1.0 pour observer le comportement du système.<br><br><h3 class="Title8 GTitle3">Terminal</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">patch -p0 &lt; module_patch_v1.0.patch</xmp></pre></div><br><h3 class="Title8 GTitle3">Terminal (Output)<br></h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">Reversed (or previously applied) patch detected!  Assume -R? [n] R</xmp></pre></div><br>Cette trace indique le patch a été déjà appliqué.<br>Dans ce cas, il est recommandé d'arrêter le processus (Ctrl + C)<br><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-1.6 - Annuler l'application d'un patch à la version v1.0"><a class="Link9" href="#Comprendre le concept des patchs">1.6 - Annuler l'application d'un patch à la version v1.0</a></h2><br>On décide d'annuler un patch appliquer à la version v1.0 par inattention.<br><br><h3 class="Title8 GTitle3">Terminal</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">patch -p0 -R &lt; module_setup_v1.0</xmp></pre></div><br><h3 class="Title8 GTitle3">Terminal (Output)</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">patching file module_setup_v1.0</xmp></pre></div><br><h3 class="Title8 GTitle3">module_setup_v1.0</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">10 + 10 = 20
10 + 30 = 40
10 + 60 = 50</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-Cas 2 : Patch à partir d'un sous-répertoire"><a class="Link9" href="#Comprendre le concept des patchs">Cas 2 : Patch à partir d'un sous-répertoire</a></h2><br>On décide de créer un patch à partir d'un sous-répertoire.<br><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-2.1 - Créer un module à la version v1.0"><a class="Link9" href="#Comprendre le concept des patchs">2.1 - Créer un module à la version v1.0</a></h2><br>On crée un module à la version v1.0.<br><br><h3 class="Title8 GTitle3">module_repo_v1.0/module_setup</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">10 + 10 = 20
10 + 30 = 40
10 + 60 = 50</xmp></pre></div><br>Après la révision du module à la version v1.0, on remarque une erreur à ligne (3).<br>On note l'erreur : <span class="GColor1" style="color:gray;">10 + 60 = 50</span><br>On définit le correctif : <span class="GColor1" style="color:teal;">10 + 60 = 70</span><br><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-2.2 - Créer un correctif à la version v1.0.1"><a class="Link9" href="#Comprendre le concept des patchs">2.2 - Créer un correctif à la version v1.0.1</a></h2><br>On crée un correctif à la version v1.0.1.<br><br><h3 class="Title8 GTitle3">module_repo_v1.0.1/module_setup</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">10 + 10 = 20
10 + 30 = 40
10 + 60 = 70</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-2.3 - Créer le path à la version v1.0"><a class="Link9" href="#Comprendre le concept des patchs">2.3 - Créer le path à la version v1.0</a></h2><br>On crée un patch à la version v1.0 entre deux fichiers.<br><br><h3 class="Title8 GTitle3">Terminal</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">diff -Naur module_repo_v1.0/ module_repo_v1.0.1/ &gt; module_patch_v1.0.patch</xmp></pre></div><br><h3 class="Title8 GTitle3">module_patch_v1.0.patch</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">diff -Naur module_repo_v1.0/module_setup module_repo_v1.0.1/module_setup
--- module_repo_v1.0/module_setup       2021-03-03 22:14:58.918006002 -0500
+++ module_repo_v1.0.1/module_setup     2021-03-03 21:10:36.386006002 -0500
@@ -1,3 +1,3 @@
 10 + 10 = 20
 10 + 30 = 40
-10 + 60 = 50
+10 + 60 = 70
</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-2.4 - Appliquer le patch à la version v1.0"><a class="Link9" href="#Comprendre le concept des patchs">2.4 - Appliquer le patch à la version v1.0</a></h2><br>On applique le patch à la version v1.0 à partir du sous-répertoire principal du module.<br><br><h3 class="Title8 GTitle3">Terminal</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">cd module_repo_v1.0/
patch -p1 &lt; ../module_patch_v1.0.patch</xmp></pre></div><br><h3 class="Title8 GTitle3">Terminal (Output)</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">patching file module_setup</xmp></pre></div><br><h3 class="Title8 GTitle3">module_repo_v1.0/module_setup</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">10 + 10 = 20
10 + 30 = 40
10 + 60 = 70</xmp></pre></div><br>On remarque que le patch s'est appliqué avec succès.<br>Le correctif a bien été installé.<br><br><h2 class="Title7 GTitle2" id="Comprendre le concept des patchs-2.5 - Réappliquer le patch à la version v1.0"><a class="Link9" href="#Comprendre le concept des patchs">2.5 - Réappliquer le patch à la version v1.0</a></h2><br>On tente de réappliquer le patch à la version v1.0 pour observer le comportement du système.<br><br><h3 class="Title8 GTitle3">Terminal</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">patch -p1 &lt; ../module_patch_v1.0.patch</xmp></pre></div><br><h3 class="Title8 GTitle3">Terminal (Output)</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">Reversed (or previously applied) patch detected!  Assume -R? [n] R</xmp></pre></div><br>Cette trace indique le patch a été déjà appliqué.<br>Dans ce cas, il est recommandé d'arrêter le processus (Ctrl + C)<br><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Voir Aussi"><a class="Link3" href="#">Voir Aussi</a></h1><div class="Body3">Dans cette même catégorie, vous pouvez consulter aussi :<br><br><span class="GColor1" style="color:lime;">Système Embarqué RaspberryPi</span><br><br><div class="Content0 GList1"><div class="Body0" id="Loader_1614775612367"><div class="Row26">List 1 &gt; Embedded_System &gt; rpi_conf</div></div><script>loadList1("Loader_1614775612367","Embedded_System","rpi_conf");</script></div><br></div></div></div></div><br>