<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Apprendre la programmation en Shell<br></div></a></div></div><div class="Body2 Orange"><br>Le but de ce tutoriel est de vous apprendre la programmation en <b>Shell</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div><br></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><br><b>Shell </b>est un interpréteur de commandes destiné aux systèmes d'exploitation de type Unix qui permet d'accéder aux fonctionnalités internes du système d'exploitation. Il se présente sous la forme d'une interface en ligne de commande accessible depuis la console ou un terminal. L'utilisateur lance des commandes sous forme d'une entrée texte exécutée ensuite par le shell.<br><br><div class="Img3 GImage"><img src="/Tutoriels/Software_Development/Shell/img/b_shell.png" alt="/Tutoriels/Software_Development/Shell/img/b_shell.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Installation"><a class="Link3" href="#">Installation</a></h1><div class="Body3"><br>Installer l'environnement Shell.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1617650179524"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1617650179524");</script></div><br><h2 class="Title7 GTitle2" id="Installation-1 - Installation sous Windows"><a class="Link9" href="#Installation">1 - Installation sous Windows</a></h2><br><h2 class="Title7 GTitle2" id="Installation-1.1 - Installation sous MSYS2"><a class="Link9" href="#Installation">1.1 - Installation sous MSYS2</a></h2><br><h2 class="Title7 GTitle2" id="Installation-1.1.1 - Télécharger MSYS2"><a class="Link9" href="#Installation">1.1.1 - Télécharger MSYS2</a></h2><br><a class="Link7 GLink1" style="color:lime;" target="_blank" href="http://repo.msys2.org/distrib/x86_64/">http://repo.msys2.org/distrib/x86_64/</a><br><br><b>msys2-x86_64-20210228.exe</b><br><br><h2 class="Title7 GTitle2" id="Installation-1.1.2 - Installer MSYS2"><a class="Link9" href="#Installation">1.1.2 - Installer MSYS2</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">msys2-x86_64-20210228.exe
Suivant
Dossier d'installation -&gt; C:\msys64
Suivant
Raccourci du menu Démarrer -&gt; MSYS2 64bit
Suivant
Suivant
Terminer</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Installation-1.1.3 - Démarrer MSYS2"><a class="Link9" href="#Installation">1.1.3 - Démarrer MSYS2</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Windows
MSYS2</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Installation-2 - Installation sous Linux"><a class="Link9" href="#Installation">2 - Installation sous Linux</a></h2><br>Aucune installation n'est nécessaire.<br><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Tests"><a class="Link3" href="#">Tests</a></h1><div class="Body3"><br>Créer un projet Shell.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1617650828720"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1617650828720");</script></div><br><h2 class="Title7 GTitle2" id="Tests-1 - Test sous Windows"><a class="Link9" href="#Tests">1 - Test sous Windows</a></h2><br><h2 class="Title7 GTitle2" id="Tests-1.1 - Test sous MSYS2"><a class="Link9" href="#Tests">1.1 - Test sous MSYS2</a></h2><br><h2 class="Title7 GTitle2" id="Tests-1.1.1 - Éditer le programme"><a class="Link9" href="#Tests">1.1.1 - Éditer le programme</a></h2><br><h3 class="Title8 GTitle3">main.sh</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">#================================================
# on affiche un message a l'ecran
echo "Bonjour tout le monde"
#================================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-1.1.2 - Exécuter le projet"><a class="Link9" href="#Tests">1.1.2 - Exécuter le projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">./main.sh</xmp></pre></div><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Bonjour tout le monde</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-2 - Test sous Linux"><a class="Link9" href="#Tests">2 - Test sous Linux</a></h2><br><h2 class="Title7 GTitle2" id="Tests-2.1 - Test sous Ubuntu"><a class="Link9" href="#Tests">2.1 - Test sous Ubuntu</a></h2><br><h2 class="Title7 GTitle2" id="Tests-2.1.1 - Éditer le programme"><a class="Link9" href="#Tests">2.1.1 - Éditer le programme</a></h2><br><h3 class="Title8 GTitle3">main.sh</h3><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">#================================================
# on affiche un message a l'ecran
echo "Bonjour tout le monde"
#================================================</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Tests-2.1.2 - Exécuter le projet"><a class="Link9" href="#Tests">2.1.2 - Exécuter le projet</a></h2><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">sudo chmod 755 main.sh</xmp></pre></div><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="sh">./main.sh</xmp></pre></div><br><div class="GCode1"><pre class="Code2"><xmp class="AceCode" data-mode="txt">Bonjour tout le monde</xmp></pre></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Système d'administration"><a class="Link3" href="#">Système d'administration</a></h1><div class="Body3"><br>Créer un système d'administration en Shell.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1617653866949"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1617653866949");</script></div><br><h2 class="Title7 GTitle2" id="Système d'administration-Introduction"><a class="Link9" href="#Système d'administration">Introduction</a></h2><br><br><br></div></div></div></div><br>