<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Apprendre la création de site internet avec Silex<br></div></a></div></div><div class="Body2 Orange">Silex est un outil de création de site internet.<br>Le but de ce tutoriel est de vous apprendre la création de site internet avec Silex.<br>Produit par <b>Gérard KESSE</b>.<br>&nbsp;<br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1529412976174"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1529412976174");</script></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Installation sous Windows"><a class="Link3" href="#">Installation sous Windows</a></h1><div class="Body3">Le but de cette section est de vous présenter les différents outils nécessaires pour apprendre la création de site internet avec Silex, sous Windows.<br>Produit par <b>Gérard KESSE</b>.<br><br>Pour le téléchargement de Silex, nous utiliserons un gestionnaire de Package PHP.<br><br>Dans ce tutoriel, nous utiliserons, sous Windows:<br>- Composer, comme gestionnaire de package PHP.<br><br><h3 class="Title8 GTitle3">Télécharger Composer</h3><a class="Link7 GLink1" style="color:lime;" href="https://getcomposer.org/">https://getcomposer.org/</a><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Installation de Composer"><a class="Link3" href="#">Installation de Composer</a></h1><div class="Body3">Le but de cette section est de vous présenter les étapes d'installation de Composer, sous Windows.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1529513464098"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1529513464098");</script></div><br><h2 class="Title7 GTitle2" id="Installation de Composer-Installation de Composer"><a class="Link9" href="#Installation de Composer">Installation de Composer</a></h2><br><h3 class="Title8 GTitle3">Installer de composer</h3><div class="GCode1"><pre><xmp class="Code2 prettyprint linenums">@echo off

set PATH=C:\wamp\bin\php\php5.6.15

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

pause</xmp></pre></div><br><h2 class="Title7 GTitle2" id="Installation de Composer-Test de Composer"><a class="Link9" href="#Installation de Composer">Test de Composer</a></h2><br><h3 class="Title8 GTitle3">Tester Composer</h3><div class="GCode1"><pre><xmp class="Code2 prettyprint linenums">@echo off

set PATH=C:\wamp\bin\php\php5.6.15

php composer.phar

pause</xmp></pre></div><br><h3 class="Title8 GTitle3">Résultat</h3><div class="Img3"><img src="img/Composer_Test.png" alt="img/Composer_Test.png"></div></div></div></div></div><br><br><br><br>