<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Mathématiques</div></a></div></div><div class="Body2 Orange">Les <b>Mathématiques </b>sont un ensemble de connaissances résultant de raisonnements logiques.<br>Le but de ce cours est de vous apprendre les <b>Mathématiques</b> appliquées aux <b>sciences de l'ingénieur</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Img3 GImage"><img src="/data/img/defaults/banner_maths.png" alt="/data/img/defaults/banner_maths.png"></div><br><div class="Content0 GSummary1"><div class="Body0" id="Loader_1530820262574"><div class="Row26">Summary 1</div></div><script>loadSummary1("Loader_1530820262574");</script></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Relation de Chasles"><a class="Link3" href="#">Relation de Chasles</a></h1><div class="Body3">La relation de Chasles est une relation permettant d'additionner deux vecteurs.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1591308213924"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1591308213924");</script></div><br><h2 class="Title7 GTitle2" id="Relation de Chasles-Calcul vectoriel"><a class="Link9" href="#Relation de Chasles">Calcul vectoriel</a></h2><br>Soient $A$, $B$ et $C$ des points de l'espace.<br><br>Relation de Chasles:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\overrightarrow{AC}  &amp;=&amp; \overrightarrow{AB}+\overrightarrow{BC}\\
\end{eqnarray}</div></div><br><h2 class="Title7 GTitle2" id="Relation de Chasles-Mesures algébriques"><a class="Link9" href="#Relation de Chasles">Mesures algébriques</a></h2><br>Soient $A$, $B$ et $C$ des points d'une droite orientée.<br><br>Relation de Chasles:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\overline{AC} &amp;=&amp; \overline{AB}+\overline{BC}
\end{eqnarray}</div></div><br><h2 class="Title7 GTitle2" id="Relation de Chasles-Angles orientés"><a class="Link9" href="#Relation de Chasles">Angles orientés</a></h2><br>Soient $\overrightarrow{u}$, $\overrightarrow{v}$ et $\overrightarrow{w}$ des vecteurs de l'espace.<br><br>Relation de Chasles:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\widehat{(\overrightarrow{u},\overrightarrow{w})} &amp;=&amp; \widehat{(\overrightarrow{u},\overrightarrow{v})} +\widehat{(\overrightarrow{v},\overrightarrow{w})} \\
\end{eqnarray}</div></div><br><h2 class="Title7 GTitle2" id="Relation de Chasles-Intégration"><a class="Link9" href="#Relation de Chasles">Intégration</a></h2><br>Soit $f$ une fonction intégrable sur un intervalle $I$.<br>Soient $a$, $b$ et $c$ des réels dans $I$.<br><br>Relation de Chasles:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\int_{a}^{c}f(x)dx &amp;=&amp; \int_{a}^{b}f(x)dx+\int_{b}^{c}f(x)dx
\end{eqnarray}</div></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Produit scalaire"><a class="Link3" href="#">Produit scalaire</a></h1><div class="Body3">Le produit scalaire est une opération algébrique s'appliquant aux vecteurs.<br>Il associe à deux vecteurs donnés un scalaire.<br><br><div class="Content0 GSummary2"><div class="Body0" id="Loader_1591312977346"><div class="Row26">Summary 2</div></div><script>loadSummary2("Loader_1591312977346");</script></div><br><h2 class="Title7 GTitle2" id="Produit scalaire-Produit scalaire"><a class="Link9" href="#Produit scalaire">Produit scalaire</a></h2><br>Soient $\overrightarrow{u}$ et $\overrightarrow{v}$ des vecteurs de l'espace.<br><br>Produit scalaire:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
A &amp;=&amp; \overrightarrow{u}.\overrightarrow{v}\\
A &amp;=&amp; \left\|\overrightarrow{u}\right\|.\left\|\overrightarrow{v}\right\|.\cos \widehat{\left ( \overrightarrow{u},\overrightarrow{u} \right )}\\
\end{eqnarray}</div></div><br><h2 class="Title7 GTitle2" id="Produit scalaire-Norme euclidienne"><a class="Link9" href="#Produit scalaire">Norme euclidienne</a></h2><br>Soit $u$ un vecteur de l'espace.<br><br>Nome euclidienne:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\overrightarrow{u}.\overrightarrow{u} &amp;=&amp; \left \| \overrightarrow{u} \right \|.\left \| \overrightarrow{u} \right \|.\cos \widehat{\left ( \overrightarrow{u},\overrightarrow{u} \right )}\\
\overrightarrow{u}.\overrightarrow{u} &amp;=&amp; \left \| \overrightarrow{u} \right \|.\left \| \overrightarrow{u} \right \|.\cos\left ( 0 \right )\\
\overrightarrow{u}.\overrightarrow{u} &amp;=&amp; \left \| \overrightarrow{u} \right \|^2\\
\end{eqnarray}</div></div><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\left \| \overrightarrow{u} \right \| &amp;=&amp; \sqrt{\overrightarrow{u}.\overrightarrow{u}}
\end{eqnarray}</div></div><br><h2 class="Title7 GTitle2" id="Produit scalaire-Inégalité de Cauchy-Schwarz"><a class="Link9" href="#Produit scalaire">Inégalité de Cauchy-Schwarz</a></h2><br>Soient $\overrightarrow{u}$ et $\overrightarrow{v}$ des vecteur de l'espace.<br><br>Inégalité de Cauchy-Schwarz:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\left | \overrightarrow{u}.\overrightarrow{v} \right | &amp;\leq&amp; \left \| \overrightarrow{u} \right \|.\left \| \overrightarrow{v} \right \|
\end{eqnarray}</div></div><br><h2 class="Title7 GTitle2" id="Produit scalaire-Théorème d'Al-Kashi"><a class="Link9" href="#Produit scalaire">Théorème d'Al-Kashi</a></h2><br><h3 class="Title8 GTitle3">Schéma descriptif</h3><br><div class="Img3 GImage"><img src="img/al_kashi.png" alt="img/al_kashi.png"></div><br>Soient $A$, $B$ et $C$ des points de l'espace.<br><br><h3 class="Title8 GTitle3">Théorème d'Al-Kashi</h3><br>Relation de Chasles:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\overrightarrow{AB} &amp;=&amp; \overrightarrow{AC}+\overrightarrow{CB}\\
\end{eqnarray}</div></div><br>Identité remarquable:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 

\overrightarrow{AB}^2 &amp;=&amp; \left (\overrightarrow{AC}+\overrightarrow{CB}  \right )^2\\
\overrightarrow{AB}^2 &amp;=&amp; \overrightarrow{AC}^2 + 2.\overrightarrow{AC}.\overrightarrow{CB}+\overrightarrow{CB}^2\\
\overrightarrow{AB}^2 &amp;=&amp; \overrightarrow{AC}^2 + 2.\left \|\overrightarrow{AC} \right \|.\left \|\overrightarrow{CB} \right \|.\cos{\widehat{\left ( \overrightarrow{AC},\overrightarrow{CB} \right )}}+\overrightarrow{CB}^2\\ \end{eqnarray}</div></div><br>Théorème d'Al-Kashi:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
c^2 &amp;=&amp; a^2+b^2+2ab\cos{\gamma}\\
\end{eqnarray}</div></div><br><h2 class="Title7 GTitle2" id="Produit scalaire-Théorème de Pythagore"><a class="Link9" href="#Produit scalaire">Théorème de Pythagore</a></h2><br><h3 class="Title8 GTitle3">Schéma descriptif</h3><br><div class="Img3 GImage"><img src="img/pythagore.png" alt="img/pythagore.png"></div><br><h3 class="Title8 GTitle3">Théorème de Pythagore</h3><br>Théorème d'Al-Kashi:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
c^2 &amp;=&amp; a^2+b^2+2ab\cos{\gamma}\\
\end{eqnarray}</div></div><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
\cos{\gamma} &amp;=&amp; \cos{90^{\circ}} &amp;=&amp; 0\\
\end{eqnarray}</div></div><br>Théorème de Pythagore:<br><br><div class="Formula GFormula1"><div class="Formula2">\begin{eqnarray} 
c^2 &amp;=&amp; a^2+b^2\\
\end{eqnarray}</div></div><br></div></div></div></div><br>