<div class="Parallax GParallax1"><div class="Img Binary"><div class="Caption"><a href="#"><div class="Text">Gestion de versions avec Mercurial<br></div></a></div></div><div class="Body2 Orange"><br>Le but de ce tutoriel est de vous apprendre la gestion de versions avec <b>Mercurial</b>.<br>Produit par <b>Gérard KESSE</b>.<br><br><div class="Content0 GSummary1"><div class="Item4"><span class="Icon10 fa fa-book"></span><a class="Link4" href="#Introduction">Introduction</a></div><div class="Item4"><span class="Icon10 fa fa-book"></span><a class="Link4" href="#Fondamentaux">Fondamentaux</a></div></div><br></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Introduction"><a class="Link3" href="#">Introduction</a></h1><div class="Body3"><br><b>Mercurial </b>est un outil de gestion de versions décentralisé.<br><br><div class="Img3 GImage"><img src="/Tutoriels/Version_Control/Mercurial/img/b_mercurial.png" alt="/Tutoriels/Version_Control/Mercurial/img/b_mercurial.png"></div><br></div></div></div></div><br><div class="Content2 GTitle1"><div class="MainBlock2"><div class="Content"><h1 class="Title2 Center" id="Fondamentaux"><a class="Link3" href="#">Fondamentaux</a></h1><div class="Body3"><br>Les fondamentaux de Mercurial.<br><br><div class="Content0 GSummary2"><div class="Item4"><i class="Icon10 fa fa-book"></i><a class="Link4" href="#Fondamentaux-Installer-l-environnement-Mercurial-sous-Windows">Installer l'environnement Mercurial sous Windows</a></div></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Installer-l-environnement-Mercurial-sous-Windows"><a class="Link9" href="#Fondamentaux">Installer l'environnement Mercurial sous Windows</a></h2><br><h3 class="Title8 GTitle3">Télécharger Mercurial</h3><br><a class="Link7 GLink1" style="color:lime;" target="_blank" href="https://www.mercurial-scm.org/release/tortoisehg/windows/tortoisehg-5.8.0-x64.msi">https://www.mercurial-scm.org/release/tortoisehg/windows/tortoisehg-5.8.0-x64.msi</a><br><br><b>tortoisehg-5.8.0-x64.msi</b><br><br><h3 class="Title8 GTitle3">Installer Mercurial</h3><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-state="off" data-mode="sh">tortoisehg-5.8.0-x64.msi
Next
Cocher -&gt; I accept the terms in the License Agreement
Next
Location -&gt; C:\Program Files\TortoiseHg\
Next
Install
Reboot -&gt; OK
Finish
Restart -&gt; Yes</pre></div></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Creer-un-depot-local"><a class="Link9" href="#Fondamentaux">Créer un dépôt local</a></h2><br>Cette opération permet de transformer un dossier local en un dépôt Mercurial.<br><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-state="off" data-mode="batchfile">cd repo
hg init</pre></div></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Cloner-un-depot-local-existant"><a class="Link9" href="#Fondamentaux">Cloner un dépôt local existant</a></h2><br>Cette opération permet de créer une copie d'un dépôt local existant.<br><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-state="off" data-mode="batchfile">hg clone file:///C:\ReadyTest\repo my_repo</pre></div></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Indexer-un-fichier"><a class="Link9" href="#Fondamentaux">Indexer un fichier</a></h2><br>Cette opération permet d'indiquer les fichiers à suivre.<br><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-state="off" data-mode="batchfile">hg add main.c</pre></div></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Renommer-un-fichier-suivi"><a class="Link9" href="#Fondamentaux">Renommer un fichier suivi</a></h2><br>Cette opération permet de renommer un fichier suivi. Elle génère une erreur lorsque le fichier n'est pas suivi.<br><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-state="off" data-mode="batchfile">hg mv Makefile Makefike.cmd.mak</pre></div></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Supprimer-un-fichier-suivi"><a class="Link9" href="#Fondamentaux">Supprimer un fichier suivi</a></h2><br>Cette opération permet de supprimer un fichier suivi. Elle génère une erreur lorsque le fichier n'est pas suivi.<br><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-state="off" data-mode="batchfile">hg rm README.md</pre></div></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Arreter-de-suivre-un-fichier"><a class="Link9" href="#Fondamentaux">Arrêter de suivre un fichier</a></h2><br>Cette opération permet de ne plus suivre un fichier déjà suivi. Elle génère une erreur lorsque le fichier n'est pas suivi.<br><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-state="off" data-mode="batchfile">hg forget README.md</pre></div></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Configurer-le-nom-de-l-utilisateur"><a class="Link9" href="#Fondamentaux">Configurer le nom de l'utilisateur</a></h2><br>Cette opération permet d'enregistrer le nom de l'utilisateur à qui sera associé les modifications.<br><br><h3 class="Title8 GTitle3">.hg/hgrc</h3><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-state="off" data-mode="batchfile">[ui]
username = Gerard KESSE &lt;tiakagerard@hotmail.com&gt;</pre></div></div><br><h2 class="Title7 GTitle2" id="Fondamentaux-Enregistrer-les-modifications-sur-fichier"><a class="Link9" href="#Fondamentaux">Enregistrer les modifications sur fichier</a></h2><br>Cette opération permet d'enregistrer les modifications réalisées sur un fichier.<br><br><div class="GCode1"><div class="Code2"><pre class="AceCode" data-state="off" data-mode="batchfile">hg commit -m "creation du programme principal" main.c</pre></div></div><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br></div></div></div></div><br>